const SEED_CARDS = [
  // ── Regular Verbs (-AR) ──────────────────────────────────────────────
  { spanish: "aceptar",    english: "to accept",        tags: ["verb","ar"] },
  { spanish: "bailar",     english: "to dance",          tags: ["verb","ar"] },
  { spanish: "bajar",      english: "to go down",        tags: ["verb","ar"] },
  { spanish: "buscar",     english: "to search for",     tags: ["verb","ar"] },
  { spanish: "caminar",    english: "to walk",           tags: ["verb","ar"] },
  { spanish: "cantar",     english: "to sing",           tags: ["verb","ar"] },
  { spanish: "cocinar",    english: "to cook",           tags: ["verb","ar"] },
  { spanish: "comprar",    english: "to buy",            tags: ["verb","ar"] },
  { spanish: "contestar",  english: "to answer",         tags: ["verb","ar"] },
  { spanish: "cortar",     english: "to cut",            tags: ["verb","ar"] },
  { spanish: "enseñar",    english: "to teach",          tags: ["verb","ar"] },
  { spanish: "entrar",     english: "to enter",          tags: ["verb","ar"] },
  { spanish: "enviar",     english: "to send",           tags: ["verb","ar"] },
  { spanish: "escuchar",   english: "to listen",         tags: ["verb","ar"] },
  { spanish: "estudiar",   english: "to study",          tags: ["verb","ar"] },
  { spanish: "gastar",     english: "to spend",          tags: ["verb","ar"] },
  { spanish: "hablar",     english: "to speak",          tags: ["verb","ar"] },
  { spanish: "lavar",      english: "to wash",           tags: ["verb","ar"] },
  { spanish: "levantar",   english: "to lift",           tags: ["verb","ar"] },
  { spanish: "limpiar",    english: "to clean",          tags: ["verb","ar"] },
  { spanish: "llegar",     english: "to arrive",         tags: ["verb","ar"] },
  { spanish: "llevar",     english: "to carry",          tags: ["verb","ar"] },
  { spanish: "llorar",     english: "to cry",            tags: ["verb","ar"] },
  { spanish: "mandar",     english: "to send",           tags: ["verb","ar"] },
  { spanish: "manejar",    english: "to drive",          tags: ["verb","ar"] },
  { spanish: "nadar",      english: "to swim",           tags: ["verb","ar"] },
  { spanish: "necesitar",  english: "to need",           tags: ["verb","ar"] },
  { spanish: "practicar",  english: "to practice",       tags: ["verb","ar"] },
  { spanish: "preparar",   english: "to prepare",        tags: ["verb","ar"] },
  { spanish: "regresar",   english: "to return",         tags: ["verb","ar"] },
  { spanish: "terminar",   english: "to finish",         tags: ["verb","ar"] },
  { spanish: "tomar",      english: "to take",           tags: ["verb","ar"] },
  { spanish: "trabajar",   english: "to work",           tags: ["verb","ar"] },
  { spanish: "usar",       english: "to use",            tags: ["verb","ar"] },
  { spanish: "viajar",     english: "to travel",         tags: ["verb","ar"] },
  // ── Regular Verbs (-ER) ──────────────────────────────────────────────
  { spanish: "aprender",   english: "to learn",          tags: ["verb","er"] },
  { spanish: "beber",      english: "to drink",          tags: ["verb","er"] },
  { spanish: "comer",      english: "to eat",            tags: ["verb","er"] },
  { spanish: "comprender", english: "to understand",     tags: ["verb","er"] },
  { spanish: "correr",     english: "to run",            tags: ["verb","er"] },
  { spanish: "creer",      english: "to think",          tags: ["verb","er"] },
  { spanish: "deber",      english: "ought to",          tags: ["verb","er"] },
  { spanish: "leer",       english: "to read",           tags: ["verb","er"] },
  { spanish: "prometer",   english: "to promise",        tags: ["verb","er"] },
  { spanish: "responder",  english: "to respond",        tags: ["verb","er"] },
  { spanish: "temer",      english: "to fear",           tags: ["verb","er"] },
  { spanish: "vender",     english: "to sell",           tags: ["verb","er"] },
  // ── Regular Verbs (-IR) ──────────────────────────────────────────────
  { spanish: "abrir",      english: "to open",           tags: ["verb","ir"] },
  { spanish: "asistir",    english: "to attend",         tags: ["verb","ir"] },
  { spanish: "decidir",    english: "to decide",         tags: ["verb","ir"] },
  { spanish: "discutir",   english: "to argue",          tags: ["verb","ir"] },
  { spanish: "escribir",   english: "to write",          tags: ["verb","ir"] },
  { spanish: "recibir",    english: "to receive",        tags: ["verb","ir"] },
  { spanish: "subir",      english: "to go up",          tags: ["verb","ir"] },
  { spanish: "vivir",      english: "to live",           tags: ["verb","ir"] },
  // ── La Casa — Bedroom ────────────────────────────────────────────────
  { spanish: "la almohada",       english: "pillow",           tags: ["house","bedroom"] },
  { spanish: "la cama",           english: "bed",              tags: ["house","bedroom"] },
  { spanish: "el closet",         english: "closet",           tags: ["house","bedroom"] },
  { spanish: "la cómoda",         english: "dresser",          tags: ["house","bedroom"] },
  { spanish: "la mesita de noche",english: "night table",      tags: ["house","bedroom"] },
  // ── La Casa — Bathroom ───────────────────────────────────────────────
  { spanish: "la bañera",         english: "bathtub",          tags: ["house","bathroom"] },
  { spanish: "la ducha",          english: "shower",           tags: ["house","bathroom"] },
  { spanish: "el espejo",         english: "mirror",           tags: ["house","bathroom"] },
  { spanish: "el jabón",          english: "soap",             tags: ["house","bathroom"] },
  { spanish: "el lavamanos",      english: "sink",             tags: ["house","bathroom"] },
  { spanish: "el retrete",        english: "toilet",           tags: ["house","bathroom"] },
  // ── La Casa — Kitchen ────────────────────────────────────────────────
  { spanish: "la alacena",        english: "cupboard",         tags: ["house","kitchen"] },
  { spanish: "el basurero",       english: "garbage can",      tags: ["house","kitchen"] },
  { spanish: "la cafetera",       english: "coffee maker",     tags: ["house","kitchen"] },
  { spanish: "el congelador",     english: "freezer",          tags: ["house","kitchen"] },
  { spanish: "la escoba",         english: "broom",            tags: ["house","kitchen"] },
  { spanish: "la estufa",         english: "stove",            tags: ["house","kitchen"] },
  { spanish: "el fregadero",      english: "sink",             tags: ["house","kitchen"] },
  { spanish: "el horno",          english: "oven",             tags: ["house","kitchen"] },
  { spanish: "el lavaplatos",     english: "dishwasher",       tags: ["house","kitchen"] },
  { spanish: "la llave",          english: "faucet",           tags: ["house","kitchen"] },
  { spanish: "el microondas",     english: "microwave",        tags: ["house","kitchen"] },
  { spanish: "las ollas",         english: "pots",             tags: ["house","kitchen"] },
  { spanish: "el refrigerador",   english: "refrigerator",     tags: ["house","kitchen"] },
  { spanish: "los sartenes",      english: "pans",             tags: ["house","kitchen"] },
  { spanish: "el tostador",       english: "toaster",          tags: ["house","kitchen"] },
  { spanish: "el trapeador",      english: "mop",              tags: ["house","kitchen"] },
  // ── La Casa — Living Room ────────────────────────────────────────────
  { spanish: "la alfombra",       english: "carpet",           tags: ["house","living room"] },
  { spanish: "la chimenea",       english: "fireplace",        tags: ["house","living room"] },
  { spanish: "el cuadro",         english: "picture",          tags: ["house","living room"] },
  { spanish: "el estéreo",        english: "stereo",           tags: ["house","living room"] },
  { spanish: "la lámpara",        english: "lamp",             tags: ["house","living room"] },
  { spanish: "el librero",        english: "bookcase",         tags: ["house","living room"] },
  { spanish: "la mesa de centro", english: "coffee table",     tags: ["house","living room"] },
  { spanish: "el reloj",          english: "clock",            tags: ["house","living room"] },
  { spanish: "la repisa",         english: "shelf",            tags: ["house","living room"] },
  { spanish: "la contestadora",   english: "answering machine", tags: ["house","living room"] },
  { spanish: "el sillón",         english: "armchair",         tags: ["house","living room"] },
  { spanish: "el sofá",           english: "sofa",             tags: ["house","living room"] },
  { spanish: "el teléfono",       english: "telephone",        tags: ["house","living room"] },
  { spanish: "la televisión",     english: "tv",               tags: ["house","living room"] },
  // ── La Casa — Dining Room ────────────────────────────────────────────
  { spanish: "los cubiertos",     english: "silverware",       tags: ["house","dining room"] },
  { spanish: "la cuchara",        english: "soup spoon",       tags: ["house","dining room"] },
  { spanish: "la cucharita",      english: "teaspoon",         tags: ["house","dining room"] },
  { spanish: "el cuchillo",       english: "knife",            tags: ["house","dining room"] },
  { spanish: "la mesa",           english: "table",            tags: ["house","dining room"] },
  { spanish: "el plato",          english: "plate",            tags: ["house","dining room"] },
  { spanish: "la silla",          english: "chair",            tags: ["house","dining room"] },
  { spanish: "la servilleta",     english: "napkin",           tags: ["house","dining room"] },
  { spanish: "la taza",           english: "cup",              tags: ["house","dining room"] },
  { spanish: "el tazón",          english: "bowl",             tags: ["house","dining room"] },
  { spanish: "el tenedor",        english: "fork",             tags: ["house","dining room"] },
  { spanish: "el vaso",           english: "glass",            tags: ["house","dining room"] },
  // ── La Casa — General ────────────────────────────────────────────────
  { spanish: "el ático",          english: "attic",            tags: ["house"] },
  { spanish: "la computadora",    english: "computer",         tags: ["house"] },
  { spanish: "las cortinas",      english: "curtains",         tags: ["house"] },
  { spanish: "la escalera",       english: "staircase",        tags: ["house"] },
  { spanish: "el escritorio",     english: "desk",             tags: ["house"] },
  { spanish: "la flor",           english: "flower",           tags: ["house"] },
  { spanish: "el florero",        english: "vase",             tags: ["house"] },
  { spanish: "el foco",           english: "light bulb",       tags: ["house"] },
  { spanish: "el garaje",         english: "garage",           tags: ["house"] },
  { spanish: "el jardín",         english: "garden",           tags: ["house"] },
  { spanish: "la lavadora",       english: "washing machine",  tags: ["house"] },
  { spanish: "la luz",            english: "light",            tags: ["house"] },
  { spanish: "la oficina",        english: "office",           tags: ["house"] },
  { spanish: "la pared",          english: "wall",             tags: ["house"] },
  { spanish: "las persianas",     english: "shades",           tags: ["house"] },
  { spanish: "el primer piso",    english: "first floor",      tags: ["house"] },
  { spanish: "los productos de limpieza", english: "cleaning products", tags: ["house"] },
  { spanish: "la puerta",         english: "door",             tags: ["house"] },
  { spanish: "la secadora",       english: "dryer",            tags: ["house"] },
  { spanish: "el segundo piso",   english: "second floor",     tags: ["house"] },
  { spanish: "el sótano",         english: "basement",         tags: ["house"] },
  { spanish: "el suelo",          english: "floor",            tags: ["house"] },
  { spanish: "el techo",          english: "ceiling",          tags: ["house"] },
  { spanish: "la ventana",        english: "window",           tags: ["house"] },
  { spanish: "el ventilador",     english: "fan",              tags: ["house"] },
];

async function seedIfEmpty() {
  const seeded = await DB.getSetting('seeded');
  if (seeded) return;
  await DB.bulkCreateCards(SEED_CARDS.map(c => ({ ...c, notes: '' })));
  await DB.setSetting('seeded', 'true');
  console.log(`Seeded ${SEED_CARDS.length} cards.`);
}

window.seedIfEmpty = seedIfEmpty;