const SEED_CARDS = [
  // ── Regular Verbs (-AR) ──────────────────────────────────────────────
  { spanish: "aceptar",    english: "to accept",        tags: ["level1","verb"] },
  { spanish: "bailar",     english: "to dance",          tags: ["level1","verb"] },
  { spanish: "bajar",      english: "to go down",        tags: ["level1","verb"] },
  { spanish: "buscar",     english: "to search for",     tags: ["level1","verb"] },
  { spanish: "caminar",    english: "to walk",           tags: ["level1","verb"] },
  { spanish: "cantar",     english: "to sing",           tags: ["level1","verb"] },
  { spanish: "cocinar",    english: "to cook",           tags: ["level1","verb"] },
  { spanish: "comprar",    english: "to buy",            tags: ["level1","verb"] },
  { spanish: "contestar",  english: "to answer",         tags: ["level1","verb"] },
  { spanish: "cortar",     english: "to cut",            tags: ["level1","verb"] },
  { spanish: "enseñar",    english: "to teach",          tags: ["level1","verb"] },
  { spanish: "entrar",     english: "to enter",          tags: ["level1","verb"] },
  { spanish: "enviar",     english: "to send",           tags: ["level1","verb"] },
  { spanish: "escuchar",   english: "to listen",         tags: ["level1","verb"] },
  { spanish: "estudiar",   english: "to study",          tags: ["level1","verb"] },
  { spanish: "gastar",     english: "to spend",          tags: ["level1","verb"] },
  { spanish: "hablar",     english: "to speak",          tags: ["level1","verb"] },
  { spanish: "lavar",      english: "to wash",           tags: ["level1","verb"] },
  { spanish: "levantar",   english: "to lift",           tags: ["level1","verb"] },
  { spanish: "limpiar",    english: "to clean",          tags: ["level1","verb"] },
  { spanish: "llegar",     english: "to arrive",         tags: ["level1","verb"] },
  { spanish: "llevar",     english: "to carry",          tags: ["level1","verb"] },
  { spanish: "llorar",     english: "to cry",            tags: ["level1","verb"] },
  { spanish: "mandar",     english: "to send",           tags: ["level1","verb"] },
  { spanish: "manejar",    english: "to drive",          tags: ["level1","verb"] },
  { spanish: "nadar",      english: "to swim",           tags: ["level1","verb"] },
  { spanish: "necesitar",  english: "to need",           tags: ["level1","verb"] },
  { spanish: "practicar",  english: "to practice",       tags: ["level1","verb"] },
  { spanish: "preparar",   english: "to prepare",        tags: ["level1","verb"] },
  { spanish: "regresar",   english: "to return",         tags: ["level1","verb"] },
  { spanish: "terminar",   english: "to finish",         tags: ["level1","verb"] },
  { spanish: "tomar",      english: "to take",           tags: ["level1","verb"] },
  { spanish: "trabajar",   english: "to work",           tags: ["level1","verb"] },
  { spanish: "usar",       english: "to use",            tags: ["level1","verb"] },
  { spanish: "viajar",     english: "to travel",         tags: ["level1","verb"] },
  // ── Regular Verbs (-ER) ──────────────────────────────────────────────
  { spanish: "aprender",   english: "to learn",          tags: ["level1","verb"] },
  { spanish: "beber",      english: "to drink",          tags: ["level1","verb"] },
  { spanish: "comer",      english: "to eat",            tags: ["level1","verb"] },
  { spanish: "comprender", english: "to understand",     tags: ["level1","verb"] },
  { spanish: "correr",     english: "to run",            tags: ["level1","verb"] },
  { spanish: "creer",      english: "to think",          tags: ["level1","verb"] },
  { spanish: "deber",      english: "ought to",          tags: ["level1","verb"] },
  { spanish: "leer",       english: "to read",           tags: ["level1","verb"] },
  { spanish: "prometer",   english: "to promise",        tags: ["level1","verb"] },
  { spanish: "responder",  english: "to respond",        tags: ["level1","verb"] },
  { spanish: "temer",      english: "to fear",           tags: ["level1","verb"] },
  { spanish: "vender",     english: "to sell",           tags: ["level1","verb"] },
  // ── Regular Verbs (-IR) ──────────────────────────────────────────────
  { spanish: "abrir",      english: "to open",           tags: ["level1","verb"] },
  { spanish: "asistir",    english: "to attend",         tags: ["level1","verb"] },
  { spanish: "decidir",    english: "to decide",         tags: ["level1","verb"] },
  { spanish: "discutir",   english: "to argue",          tags: ["level1","verb"] },
  { spanish: "escribir",   english: "to write",          tags: ["level1","verb"] },
  { spanish: "recibir",    english: "to receive",        tags: ["level1","verb"] },
  { spanish: "subir",      english: "to go up",          tags: ["level1","verb"] },
  { spanish: "vivir",      english: "to live",           tags: ["level1","verb"] },
  // ── La Casa — Bedroom ────────────────────────────────────────────────
  { spanish: "la almohada",        english: "pillow",           tags: ["level1","house"] },
  { spanish: "la cama",            english: "bed",              tags: ["level1","house"] },
  { spanish: "el closet",          english: "closet",           tags: ["level1","house"] },
  { spanish: "la cómoda",          english: "dresser",          tags: ["level1","house"] },
  { spanish: "la mesita de noche", english: "night table",      tags: ["level1","house"] },
  // ── La Casa — Bathroom ───────────────────────────────────────────────
  { spanish: "la bañera",          english: "bathtub",          tags: ["level1","house"] },
  { spanish: "la ducha",           english: "shower",           tags: ["level1","house"] },
  { spanish: "el espejo",          english: "mirror",           tags: ["level1","house"] },
  { spanish: "el jabón",           english: "soap",             tags: ["level1","house"] },
  { spanish: "el lavamanos",       english: "sink",             tags: ["level1","house"] },
  { spanish: "el retrete",         english: "toilet",           tags: ["level1","house"] },
  // ── La Casa — Kitchen ────────────────────────────────────────────────
  { spanish: "la alacena",         english: "cupboard",         tags: ["level1","house"] },
  { spanish: "el basurero",        english: "garbage can",      tags: ["level1","house"] },
  { spanish: "la cafetera",        english: "coffee maker",     tags: ["level1","house"] },
  { spanish: "el congelador",      english: "freezer",          tags: ["level1","house"] },
  { spanish: "la escoba",          english: "broom",            tags: ["level1","house"] },
  { spanish: "la estufa",          english: "stove",            tags: ["level1","house"] },
  { spanish: "el fregadero",       english: "sink",             tags: ["level1","house"] },
  { spanish: "el horno",           english: "oven",             tags: ["level1","house"] },
  { spanish: "el lavaplatos",      english: "dishwasher",       tags: ["level1","house"] },
  { spanish: "la llave",           english: "faucet",           tags: ["level1","house"] },
  { spanish: "el microondas",      english: "microwave",        tags: ["level1","house"] },
  { spanish: "las ollas",          english: "pots",             tags: ["level1","house"] },
  { spanish: "el refrigerador",    english: "refrigerator",     tags: ["level1","house"] },
  { spanish: "los sartenes",       english: "pans",             tags: ["level1","house"] },
  { spanish: "el tostador",        english: "toaster",          tags: ["level1","house"] },
  { spanish: "el trapeador",       english: "mop",              tags: ["level1","house"] },
  // ── La Casa — Living Room ────────────────────────────────────────────
  { spanish: "la alfombra",        english: "carpet",           tags: ["level1","house"] },
  { spanish: "la chimenea",        english: "fireplace",        tags: ["level1","house"] },
  { spanish: "el cuadro",          english: "picture",          tags: ["level1","house"] },
  { spanish: "el estéreo",         english: "stereo",           tags: ["level1","house"] },
  { spanish: "la lámpara",         english: "lamp",             tags: ["level1","house"] },
  { spanish: "el librero",         english: "bookcase",         tags: ["level1","house"] },
  { spanish: "la mesa de centro",  english: "coffee table",     tags: ["level1","house"] },
  { spanish: "el reloj",           english: "clock",            tags: ["level1","house"] },
  { spanish: "la repisa",          english: "shelf",            tags: ["level1","house"] },
  { spanish: "la contestadora",    english: "answering machine", tags: ["level1","house"] },
  { spanish: "el sillón",          english: "armchair",         tags: ["level1","house"] },
  { spanish: "el sofá",            english: "sofa",             tags: ["level1","house"] },
  { spanish: "el teléfono",        english: "telephone",        tags: ["level1","house"] },
  { spanish: "la televisión",      english: "tv",               tags: ["level1","house"] },
  // ── La Casa — Dining Room ────────────────────────────────────────────
  { spanish: "los cubiertos",      english: "silverware",       tags: ["level1","house"] },
  { spanish: "la cuchara",         english: "soup spoon",       tags: ["level1","house"] },
  { spanish: "la cucharita",       english: "teaspoon",         tags: ["level1","house"] },
  { spanish: "el cuchillo",        english: "knife",            tags: ["level1","house"] },
  { spanish: "la mesa",            english: "table",            tags: ["level1","house"] },
  { spanish: "el plato",           english: "plate",            tags: ["level1","house"] },
  { spanish: "la silla",           english: "chair",            tags: ["level1","house"] },
  { spanish: "la servilleta",      english: "napkin",           tags: ["level1","house"] },
  { spanish: "la taza",            english: "cup",              tags: ["level1","house"] },
  { spanish: "el tazón",           english: "bowl",             tags: ["level1","house"] },
  { spanish: "el tenedor",         english: "fork",             tags: ["level1","house"] },
  { spanish: "el vaso",            english: "glass",            tags: ["level1","house"] },
  // ── La Casa — General ────────────────────────────────────────────────
  { spanish: "el ático",           english: "attic",            tags: ["level1","house"] },
  { spanish: "la computadora",     english: "computer",         tags: ["level1","house"] },
  { spanish: "las cortinas",       english: "curtains",         tags: ["level1","house"] },
  { spanish: "la escalera",        english: "staircase",        tags: ["level1","house"] },
  { spanish: "el escritorio",      english: "desk",             tags: ["level1","house"] },
  { spanish: "la flor",            english: "flower",           tags: ["level1","house"] },
  { spanish: "el florero",         english: "vase",             tags: ["level1","house"] },
  { spanish: "el foco",            english: "light bulb",       tags: ["level1","house"] },
  { spanish: "el garaje",          english: "garage",           tags: ["level1","house"] },
  { spanish: "el jardín",          english: "garden",           tags: ["level1","house"] },
  { spanish: "la lavadora",        english: "washing machine",  tags: ["level1","house"] },
  { spanish: "la luz",             english: "light",            tags: ["level1","house"] },
  { spanish: "la oficina",         english: "office",           tags: ["level1","house"] },
  { spanish: "la pared",           english: "wall",             tags: ["level1","house"] },
  { spanish: "las persianas",      english: "shades",           tags: ["level1","house"] },
  { spanish: "el primer piso",     english: "first floor",      tags: ["level1","house"] },
  { spanish: "los productos de limpieza", english: "cleaning products", tags: ["level1","house"] },
  { spanish: "la puerta",          english: "door",             tags: ["level1","house"] },
  { spanish: "la secadora",        english: "dryer",            tags: ["level1","house"] },
  { spanish: "el segundo piso",    english: "second floor",     tags: ["level1","house"] },
  { spanish: "el sótano",          english: "basement",         tags: ["level1","house"] },
  { spanish: "el suelo",           english: "floor",            tags: ["level1","house"] },
  { spanish: "el techo",           english: "ceiling",          tags: ["level1","house"] },
  { spanish: "la ventana",         english: "window",           tags: ["level1","house"] },
  { spanish: "el ventilador",      english: "fan",              tags: ["level1","house"] },
  // ── Clothing ─────────────────────────────────────────────────────────
  { spanish: "el abrigo",          english: "coat",             tags: ["level1","clothing"] },
  { spanish: "la cartera",         english: "purse",            tags: ["level1","clothing"] },
  { spanish: "la billetera",       english: "wallet",           tags: ["level1","clothing"] },
  { spanish: "el cinturón",        english: "belt",             tags: ["level1","clothing"] },
  { spanish: "el paraguas",        english: "umbrella",         tags: ["level1","clothing"] },
  { spanish: "el sombrero",        english: "hat",              tags: ["level1","clothing"] },
  { spanish: "el suéter",          english: "sweater",          tags: ["level1","clothing"] },
  { spanish: "el traje",           english: "suit",             tags: ["level1","clothing"] },
  { spanish: "el traje de baño",   english: "bathing suit",     tags: ["level1","clothing"] },
  { spanish: "el vestido",         english: "dress",            tags: ["level1","clothing"] },
  { spanish: "el zapato",          english: "shoe",             tags: ["level1","clothing"] },
  { spanish: "la blusa",           english: "blouse",           tags: ["level1","clothing"] },
  { spanish: "la camisa",          english: "shirt",            tags: ["level1","clothing"] },
  { spanish: "la camiseta",        english: "t-shirt",          tags: ["level1","clothing"] },
  { spanish: "la chaqueta",        english: "jacket",           tags: ["level1","clothing"] },
  { spanish: "la corbata",         english: "tie",              tags: ["level1","clothing"] },
  { spanish: "la falda",           english: "skirt",            tags: ["level1","clothing"] },
  { spanish: "la gorra",           english: "cap",              tags: ["level1","clothing"] },
  { spanish: "las botas",          english: "boots",            tags: ["level1","clothing"] },
  { spanish: "las sandalias",      english: "sandals",          tags: ["level1","clothing"] },
  { spanish: "los calcetines",     english: "socks",            tags: ["level1","clothing"] },
  { spanish: "los jeans",          english: "jeans",            tags: ["level1","clothing"] },
  { spanish: "los pantalones",     english: "pants",            tags: ["level1","clothing"] },
  { spanish: "las bermudas",       english: "shorts",           tags: ["level1","clothing"] },
  { spanish: "los tenis",          english: "sneakers",         tags: ["level1","clothing"] },
  { spanish: "la pijama",          english: "pajama",           tags: ["level1","clothing"] },
  { spanish: "el brasiere",        english: "bra",              tags: ["level1","clothing"] },
  { spanish: "los calzones",       english: "women's underwear", tags: ["level1","clothing"] },
  { spanish: "los calzoncillos",   english: "men's underwear",  tags: ["level1","clothing"] },
  { spanish: "la bufanda",         english: "scarf",            tags: ["level1","clothing"] },
  { spanish: "los guantes",        english: "gloves",           tags: ["level1","clothing"] },
  { spanish: "el saco",            english: "sport jacket",     tags: ["level1","clothing"] },
  { spanish: "el chaleco",         english: "vest",             tags: ["level1","clothing"] },
  // ── Numbers ───────────────────────────────────────────────────────────
  { spanish: "cero",               english: "0, zero",          tags: ["level1","number"] },
  { spanish: "uno",                english: "1, one",           tags: ["level1","number"] },
  { spanish: "dos",                english: "2, two",           tags: ["level1","number"] },
  { spanish: "tres",               english: "3, three",         tags: ["level1","number"] },
  { spanish: "cuatro",             english: "4, four",          tags: ["level1","number"] },
  { spanish: "cinco",              english: "5, five",          tags: ["level1","number"] },
  { spanish: "seis",               english: "6, six",           tags: ["level1","number"] },
  { spanish: "siete",              english: "7, seven",         tags: ["level1","number"] },
  { spanish: "ocho",               english: "8, eight",         tags: ["level1","number"] },
  { spanish: "nueve",              english: "9, nine",          tags: ["level1","number"] },
  { spanish: "diez",               english: "10, ten",          tags: ["level1","number"] },
  { spanish: "once",               english: "11, eleven",       tags: ["level1","number"] },
  { spanish: "doce",               english: "12, twelve",       tags: ["level1","number"] },
  { spanish: "trece",              english: "13, thirteen",     tags: ["level1","number"] },
  { spanish: "catorce",            english: "14, fourteen",     tags: ["level1","number"] },
  { spanish: "quince",             english: "15, fifteen",      tags: ["level1","number"] },
  { spanish: "dieciséis",          english: "16, sixteen",      tags: ["level1","number"] },
  { spanish: "diecisiete",         english: "17, seventeen",    tags: ["level1","number"] },
  { spanish: "dieciocho",          english: "18, eighteen",     tags: ["level1","number"] },
  { spanish: "diecinueve",         english: "19, nineteen",     tags: ["level1","number"] },
  { spanish: "veinte",             english: "20, twenty",       tags: ["level1","number"] },
  { spanish: "veintiuno",          english: "21, twenty-one",   tags: ["level1","number"] },
  { spanish: "veintidós",          english: "22, twenty-two",   tags: ["level1","number"] },
  { spanish: "veintitrés",         english: "23, twenty-three", tags: ["level1","number"] },
  { spanish: "veinticuatro",       english: "24, twenty-four",  tags: ["level1","number"] },
  { spanish: "veinticinco",        english: "25, twenty-five",  tags: ["level1","number"] },
  { spanish: "veintiséis",         english: "26, twenty-six",   tags: ["level1","number"] },
  { spanish: "veintisiete",        english: "27, twenty-seven", tags: ["level1","number"] },
  { spanish: "veintiocho",         english: "28, twenty-eight", tags: ["level1","number"] },
  { spanish: "veintinueve",        english: "29, twenty-nine",  tags: ["level1","number"] },
  { spanish: "treinta",            english: "30, thirty",       tags: ["level1","number"] },
  { spanish: "treinta y uno",      english: "31, thirty-one",   tags: ["level1","number"] },
  { spanish: "treinta y dos",      english: "32, thirty-two",   tags: ["level1","number"] },
  { spanish: "treinta y tres",     english: "33, thirty-three", tags: ["level1","number"] },
  { spanish: "treinta y cuatro",   english: "34, thirty-four",  tags: ["level1","number"] },
  { spanish: "treinta y cinco",    english: "35, thirty-five",  tags: ["level1","number"] },
  { spanish: "treinta y seis",     english: "36, thirty-six",   tags: ["level1","number"] },
  { spanish: "treinta y siete",    english: "37, thirty-seven", tags: ["level1","number"] },
  { spanish: "treinta y ocho",     english: "38, thirty-eight", tags: ["level1","number"] },
  { spanish: "treinta y nueve",    english: "39, thirty-nine",  tags: ["level1","number"] },
  { spanish: "cuarenta",           english: "40, forty",        tags: ["level1","number"] },
  { spanish: "cincuenta",          english: "50, fifty",        tags: ["level1","number"] },
  { spanish: "sesenta",            english: "60, sixty",        tags: ["level1","number"] },
  { spanish: "setenta",            english: "70, seventy",      tags: ["level1","number"] },
  { spanish: "ochenta",            english: "80, eighty",       tags: ["level1","number"] },
  { spanish: "noventa",            english: "90, ninety",       tags: ["level1","number"] },
  { spanish: "cien",               english: "100, one hundred", tags: ["level1","number"] },
  // ── Professions ───────────────────────────────────────────────────────
  { spanish: "abogado(a)",         english: "lawyer",           tags: ["level1","profession"] },
  { spanish: "actor/actriz",       english: "actor/actress",    tags: ["level1","profession"] },
  { spanish: "agente inmobiliario",english: "real estate agent", tags: ["level1","profession"] },
  { spanish: "ama de casa",        english: "housewife",        tags: ["level1","profession"] },
  { spanish: "arquitecto(a)",      english: "architect",        tags: ["level1","profession"] },
  { spanish: "cantante",           english: "singer",           tags: ["level1","profession"] },
  { spanish: "contador(a)",        english: "accountant",       tags: ["level1","profession"] },
  { spanish: "dentista",           english: "dentist",          tags: ["level1","profession"] },
  { spanish: "doctor(a)",          english: "doctor",           tags: ["level1","profession"] },
  { spanish: "enfermero(a)",       english: "nurse",            tags: ["level1","profession"] },
  { spanish: "escritor(a)",        english: "writer",           tags: ["level1","profession"] },
  { spanish: "gerente",            english: "manager",          tags: ["level1","profession"] },
  { spanish: "ingeniero(a)",       english: "engineer",         tags: ["level1","profession"] },
  { spanish: "maestro(a)",         english: "teacher",          tags: ["level1","profession"] },
  { spanish: "secretario(a)",      english: "secretary",        tags: ["level1","profession"] },
  { spanish: "trabajador(a) social",english: "social worker",   tags: ["level1","profession"] },
  { spanish: "vendedor(a)",        english: "salesperson",      tags: ["level1","profession"] },
  // ── Physical Adjectives (ser) ─────────────────────────────────────────
  { spanish: "alto(a)",            english: "tall",             tags: ["level1","adjective","physical"] },
  { spanish: "bajo(a)",            english: "short",            tags: ["level1","adjective","physical"] },
  { spanish: "bonito(a)",          english: "beautiful",        tags: ["level1","adjective","physical"] },
  { spanish: "calvo(a)",           english: "bald",             tags: ["level1","adjective","physical"] },
  { spanish: "de estatura media",  english: "medium height",    tags: ["level1","adjective","physical"] },
  { spanish: "de contextura media",english: "medium built",     tags: ["level1","adjective","physical"] },
  { spanish: "delgado(a)",         english: "slim",             tags: ["level1","adjective","physical"] },
  { spanish: "flaco(a)",           english: "skinny",           tags: ["level1","adjective","physical"] },
  { spanish: "feo(a)",             english: "ugly",             tags: ["level1","adjective","physical"] },
  { spanish: "gordo(a)",           english: "fat",              tags: ["level1","adjective","physical"] },
  { spanish: "grande",             english: "big",              tags: ["level1","adjective","physical"] },
  { spanish: "guapo(a)",           english: "good looking",     tags: ["level1","adjective","physical"] },
  { spanish: "joven",              english: "young",            tags: ["level1","adjective","physical"] },
  { spanish: "largo(a)",           english: "long",             tags: ["level1","adjective","physical"] },
  { spanish: "lindo(a)",           english: "cute",             tags: ["level1","adjective","physical"] },
  { spanish: "pequeño(a)",         english: "little",           tags: ["level1","adjective","physical"] },
  { spanish: "viejo(a)",           english: "old",              tags: ["level1","adjective","physical"] },
  // ── Personality Adjectives (ser) ──────────────────────────────────────
  { spanish: "aburrido(a)",        english: "boring",           tags: ["level1","adjective","personality"] },
  { spanish: "amable",             english: "kind",             tags: ["level1","adjective","personality"] },
  { spanish: "amigable",           english: "friendly",         tags: ["level1","adjective","personality"] },
  { spanish: "antipático(a)",      english: "unpleasant",       tags: ["level1","adjective","personality"] },
  { spanish: "atento(a)",          english: "attentive",        tags: ["level1","adjective","personality"] },
  { spanish: "bueno(a)",           english: "good",             tags: ["level1","adjective","personality"] },
  { spanish: "callado(a)",         english: "quiet",            tags: ["level1","adjective","personality"] },
  { spanish: "cariñoso(a)",        english: "affectionate",     tags: ["level1","adjective","personality"] },
  { spanish: "chistoso(a)",        english: "funny",            tags: ["level1","adjective","personality"] },
  { spanish: "divertido(a)",       english: "fun",              tags: ["level1","adjective","personality"] },
  { spanish: "extrovertido(a)",    english: "extroverted",      tags: ["level1","adjective","personality"] },
  { spanish: "inteligente",        english: "intelligent",      tags: ["level1","adjective","personality"] },
  { spanish: "interesante",        english: "interesting",      tags: ["level1","adjective","personality"] },
  { spanish: "listo(a)",           english: "smart",            tags: ["level1","adjective","personality"] },
  { spanish: "malo(a)",            english: "bad",              tags: ["level1","adjective","personality"] },
  { spanish: "paciente",           english: "patient",          tags: ["level1","adjective","personality"] },
  { spanish: "perezoso(a)",        english: "lazy",             tags: ["level1","adjective","personality"] },
  { spanish: "responsable",        english: "responsible",      tags: ["level1","adjective","personality"] },
  { spanish: "romántico(a)",       english: "romantic",         tags: ["level1","adjective","personality"] },
  { spanish: "serio(a)",           english: "serious",          tags: ["level1","adjective","personality"] },
  { spanish: "simpático(a)",       english: "nice",             tags: ["level1","adjective","personality"] },
  { spanish: "tierno(a)",          english: "loving",           tags: ["level1","adjective","personality"] },
  { spanish: "tímido(a)",          english: "shy",              tags: ["level1","adjective","personality"] },
  { spanish: "tonto(a)",           english: "dumb",             tags: ["level1","adjective","personality"] },
  { spanish: "trabajador(a)",      english: "hardworking",      tags: ["level1","adjective","personality"] },
  // ── Religion & Politics ───────────────────────────────────────────────
  { spanish: "bautista",           english: "baptist",          tags: ["level1","adjective","religion"] },
  { spanish: "católico(a)",        english: "catholic",         tags: ["level1","adjective","religion"] },
  { spanish: "judío(a)",           english: "jewish",           tags: ["level1","adjective","religion"] },
  { spanish: "luterano(a)",        english: "lutheran",         tags: ["level1","adjective","religion"] },
  { spanish: "metodista",          english: "methodist",        tags: ["level1","adjective","religion"] },
  { spanish: "musulmán(a)",        english: "muslim",           tags: ["level1","adjective","religion"] },
  { spanish: "protestante",        english: "protestant",       tags: ["level1","adjective","religion"] },
  { spanish: "cristiano",          english: "christian",        tags: ["level1","adjective","religion"] },
  { spanish: "demócrata",          english: "democrat",         tags: ["level1","adjective","politics"] },
  { spanish: "republicano(a)",     english: "republican",       tags: ["level1","adjective","politics"] },
  { spanish: "independiente",      english: "independent",      tags: ["level1","adjective","politics"] },
  // ── Colors ────────────────────────────────────────────────────────────
  { spanish: "amarillo(a)",        english: "yellow",           tags: ["level1","color","adjective"] },
  { spanish: "azul",               english: "blue",             tags: ["level1","color","adjective"] },
  { spanish: "beige",              english: "beige",            tags: ["level1","color","adjective"] },
  { spanish: "blanco(a)",          english: "white",            tags: ["level1","color","adjective"] },
  { spanish: "café",               english: "brown",            tags: ["level1","color","adjective"] },
  { spanish: "gris",               english: "grey",             tags: ["level1","color","adjective"] },
  { spanish: "morado(a)",          english: "purple",           tags: ["level1","color","adjective"] },
  { spanish: "naranja",            english: "orange",           tags: ["level1","color","adjective"] },
  { spanish: "negro(a)",           english: "black",            tags: ["level1","color","adjective"] },
  { spanish: "rojo(a)",            english: "red",              tags: ["level1","color","adjective"] },
  { spanish: "rosado(a)",          english: "pink",             tags: ["level1","color","adjective"] },
  { spanish: "verde",              english: "green",            tags: ["level1","color","adjective"] },
  // ── Family & Relationships ────────────────────────────────────────────
  { spanish: "abuelo(a)",          english: "grandfather/grandmother", tags: ["level1","family"] },
  { spanish: "amigo(a)",           english: "friend",           tags: ["level1","family"] },
  { spanish: "esposo(a)",          english: "spouse",           tags: ["level1","family"] },
  { spanish: "hermano(a)",         english: "brother/sister",   tags: ["level1","family"] },
  { spanish: "hijo(a)",            english: "son/daughter",     tags: ["level1","family"] },
  { spanish: "madre",              english: "mother",           tags: ["level1","family"] },
  { spanish: "novio(a)",           english: "boyfriend/girlfriend", tags: ["level1","family"] },
  { spanish: "padre",              english: "father",           tags: ["level1","family"] },
  { spanish: "primo(a)",           english: "cousin",           tags: ["level1","family"] },
  { spanish: "sobrino(a)",         english: "nephew/niece",     tags: ["level1","family"] },
  { spanish: "tío(a)",             english: "uncle/aunt",       tags: ["level1","family"] },
  { spanish: "prometida",          english: "fiancee",          tags: ["level1","family"] },
  { spanish: "yerno",              english: "son-in-law",       tags: ["level1","family"] },
  { spanish: "nuera",              english: "daughter-in-law",  tags: ["level1","family"] },
  { spanish: "suegro(a)",          english: "mother/father-in-law", tags: ["level1","family"] },
  // ── Materials ─────────────────────────────────────────────────────────
  { spanish: "algodón",            english: "cotton",           tags: ["level1","material"] },
  { spanish: "cuero",              english: "leather",          tags: ["level1","material"] },
  { spanish: "madera",             english: "wood",             tags: ["level1","material"] },
  { spanish: "metal",              english: "metal",            tags: ["level1","material"] },
  { spanish: "oro",                english: "gold",             tags: ["level1","material"] },
  { spanish: "plástico",           english: "plastic",          tags: ["level1","material"] },
  { spanish: "plata",              english: "silver",           tags: ["level1","material"] },
  { spanish: "seda",               english: "silk",             tags: ["level1","material"] },
  { spanish: "tela",               english: "fabric",           tags: ["level1","material"] },
  { spanish: "vidrio",             english: "glass",            tags: ["level1","material"] },
  // ── Days of the Week ──────────────────────────────────────────────────
  { spanish: "lunes",              english: "Monday",           tags: ["level1","days"] },
  { spanish: "martes",             english: "Tuesday",          tags: ["level1","days"] },
  { spanish: "miércoles",          english: "Wednesday",        tags: ["level1","days"] },
  { spanish: "jueves",             english: "Thursday",         tags: ["level1","days"] },
  { spanish: "viernes",            english: "Friday",           tags: ["level1","days"] },
  { spanish: "sábado",             english: "Saturday",         tags: ["level1","days"] },
  { spanish: "domingo",            english: "Sunday",           tags: ["level1","days"] },
  // ── Months ────────────────────────────────────────────────────────────
  { spanish: "enero",              english: "January",          tags: ["level1","months"] },
  { spanish: "febrero",            english: "February",         tags: ["level1","months"] },
  { spanish: "marzo",              english: "March",            tags: ["level1","months"] },
  { spanish: "abril",              english: "April",            tags: ["level1","months"] },
  { spanish: "mayo",               english: "May",              tags: ["level1","months"] },
  { spanish: "junio",              english: "June",             tags: ["level1","months"] },
  { spanish: "julio",              english: "July",             tags: ["level1","months"] },
  { spanish: "agosto",             english: "August",           tags: ["level1","months"] },
  { spanish: "septiembre",         english: "September",        tags: ["level1","months"] },
  { spanish: "octubre",            english: "October",          tags: ["level1","months"] },
  { spanish: "noviembre",          english: "November",         tags: ["level1","months"] },
  { spanish: "diciembre",          english: "December",         tags: ["level1","months"] },
  // ── Estar Adjectives (Emotional) ──────────────────────────────────────
  { spanish: "triste",             english: "sad",              tags: ["level1","adjective","emotion"] },
  { spanish: "feliz",              english: "happy",            tags: ["level1","adjective","emotion"] },
  { spanish: "cansado(a)",         english: "tired",            tags: ["level1","adjective","emotion"] },
  { spanish: "enfermo(a)",         english: "sick",             tags: ["level1","adjective","emotion"] },
  { spanish: "enojado(a)",         english: "angry",            tags: ["level1","adjective","emotion"] },
  { spanish: "nervioso(a)",        english: "nervous",          tags: ["level1","adjective","emotion"] },
  { spanish: "preocupado(a)",      english: "worried",          tags: ["level1","adjective","emotion"] },
  { spanish: "ocupado(a)",         english: "busy",             tags: ["level1","adjective","emotion"] },
  { spanish: "enamorado(a)",       english: "in love",          tags: ["level1","adjective","emotion"] },
  // ── Other Estar Adjectives ────────────────────────────────────────────
  { spanish: "descompuesto(a)",    english: "out of order",     tags: ["level1","adjective"] },
  { spanish: "desordenado(a)",     english: "unorganized",      tags: ["level1","adjective"] },
  { spanish: "ordenado(a)",        english: "neat",             tags: ["level1","adjective"] },
  { spanish: "limpio(a)",          english: "clean",            tags: ["level1","adjective"] },
  { spanish: "sucio(a)",           english: "dirty",            tags: ["level1","adjective"] },
  { spanish: "roto(a)",            english: "broken",           tags: ["level1","adjective"] },
  { spanish: "abierto(a)",         english: "open",             tags: ["level1","adjective"] },
  { spanish: "cerrado(a)",         english: "closed",           tags: ["level1","adjective"] },
  // ── El Cuerpo (Body) ──────────────────────────────────────────────────
  { spanish: "la cabeza",          english: "head",             tags: ["level2","body"] },
  { spanish: "el ojo",             english: "eye",              tags: ["level2","body"] },
  { spanish: "la nariz",           english: "nose",             tags: ["level2","body"] },
  { spanish: "la boca",            english: "mouth",            tags: ["level2","body"] },
  { spanish: "los labios",         english: "lips",             tags: ["level2","body"] },
  { spanish: "los dientes",        english: "teeth",            tags: ["level2","body"] },
  { spanish: "la lengua",          english: "tongue",           tags: ["level2","body"] },
  { spanish: "la oreja",           english: "ear (outer)",      tags: ["level2","body"] },
  { spanish: "el oído",            english: "ear (inner)",      tags: ["level2","body"] },
  { spanish: "la mejilla",         english: "cheek",            tags: ["level2","body"] },
  { spanish: "el pelo",            english: "hair",             tags: ["level2","body"] },
  { spanish: "el cabello",         english: "hair (head)",      tags: ["level2","body"] },
  { spanish: "la ceja",            english: "eyebrow",          tags: ["level2","body"] },
  { spanish: "las pestañas",       english: "eyelashes",        tags: ["level2","body"] },
  { spanish: "el mentón",          english: "chin",             tags: ["level2","body"] },
  { spanish: "la frente",          english: "forehead",         tags: ["level2","body"] },
  { spanish: "el cuello",          english: "neck",             tags: ["level2","body"] },
  { spanish: "la nuca",            english: "back of neck",     tags: ["level2","body"] },
  { spanish: "el hombro",          english: "shoulder",         tags: ["level2","body"] },
  { spanish: "el pecho",           english: "chest",            tags: ["level2","body"] },
  { spanish: "la espalda",         english: "back",             tags: ["level2","body"] },
  { spanish: "el brazo",           english: "arm",              tags: ["level2","body"] },
  { spanish: "el codo",            english: "elbow",            tags: ["level2","body"] },
  { spanish: "la muñeca",          english: "wrist",            tags: ["level2","body"] },
  { spanish: "la mano",            english: "hand",             tags: ["level2","body"] },
  { spanish: "el dedo",            english: "finger",           tags: ["level2","body"] },
  { spanish: "la uña",             english: "nail",             tags: ["level2","body"] },
  { spanish: "el estómago",        english: "stomach",          tags: ["level2","body"] },
  { spanish: "el ombligo",         english: "belly button",     tags: ["level2","body"] },
  { spanish: "las caderas",        english: "hips",             tags: ["level2","body"] },
  { spanish: "la cintura",         english: "waist",            tags: ["level2","body"] },
  { spanish: "los pompis",         english: "buns",             tags: ["level2","body"] },
  { spanish: "las nalgas",         english: "buns",             tags: ["level2","body"] },
  { spanish: "el muslo",           english: "thigh",            tags: ["level2","body"] },
  { spanish: "la pierna",          english: "leg",              tags: ["level2","body"] },
  { spanish: "la rodilla",         english: "knee",             tags: ["level2","body"] },
  { spanish: "el tobillo",         english: "ankle",            tags: ["level2","body"] },
  { spanish: "el pie",             english: "foot",             tags: ["level2","body"] },
  { spanish: "el dedo del pie",    english: "toe",              tags: ["level2","body"] },
  { spanish: "la planta del pie",  english: "bottom of foot",   tags: ["level2","body"] },

  // ── Irregular Verbs ──────────────────────────────────────────────────
  // Irregular in yo only
  { spanish: "conocer",            english: "to know (a person or place)", tags: ["level2","verb","irregular verb"] },
  { spanish: "dar",                english: "to give",           tags: ["level2","verb","irregular verb"] },
  { spanish: "hacer",              english: "to do, to make",    tags: ["level2","verb","irregular verb"] },
  { spanish: "poner",              english: "to put, to place",  tags: ["level2","verb","irregular verb"] },
  { spanish: "saber",              english: "to know (information)", tags: ["level2","verb","irregular verb"] },
  { spanish: "salir",              english: "to leave, to go out", tags: ["level2","verb","irregular verb"] },
  { spanish: "traer",              english: "to bring",          tags: ["level2","verb","irregular verb"] },
  { spanish: "ver",                english: "to see, to watch",  tags: ["level2","verb","irregular verb"] },
  // Highly irregular
  { spanish: "decir",              english: "to say, to tell",   tags: ["level2","verb","irregular verb"] },
  { spanish: "venir",              english: "to come",           tags: ["level2","verb","irregular verb"] },
  // e → ie stem change
  { spanish: "preferir",           english: "to prefer",         tags: ["level2","verb","irregular verb"] },
  { spanish: "querer",             english: "to want, to love",  tags: ["level2","verb","irregular verb"] },
  { spanish: "cerrar",             english: "to close",          tags: ["level2","verb","irregular verb"] },
  { spanish: "pensar",             english: "to think",          tags: ["level2","verb","irregular verb"] },
  { spanish: "comenzar",           english: "to begin",          tags: ["level2","verb","irregular verb"] },
  { spanish: "empezar",            english: "to begin",          tags: ["level2","verb","irregular verb"] },
  { spanish: "entender",           english: "to understand",     tags: ["level2","verb","irregular verb"] },
  { spanish: "perder",             english: "to lose",           tags: ["level2","verb","irregular verb"] },
  // o → ue stem change
  { spanish: "recordar",           english: "to remember",       tags: ["level2","verb","irregular verb"] },
  { spanish: "jugar",              english: "to play",           tags: ["level2","verb","irregular verb"] },
  { spanish: "devolver",           english: "to return (something)", tags: ["level2","verb","irregular verb"] },
  { spanish: "dormir",             english: "to sleep",          tags: ["level2","verb","irregular verb"] },
  { spanish: "volver",             english: "to return",         tags: ["level2","verb","irregular verb"] },
  { spanish: "poder",              english: "to be able to, can", tags: ["level2","verb","irregular verb"] },
  // e → i stem change
  { spanish: "servir",             english: "to serve",          tags: ["level2","verb","irregular verb"] },
  { spanish: "pedir",              english: "to ask for",        tags: ["level2","verb","irregular verb"] },
  { spanish: "seguir",             english: "to follow, to continue", tags: ["level2","verb","irregular verb"] },
  { spanish: "conseguir",          english: "to get",            tags: ["level2","verb","irregular verb"] },
  { spanish: "repetir",            english: "to repeat",         tags: ["level2","verb","irregular verb"] },

  // ── Tener expressions ────────────────────────────────────────────────
  { spanish: "tener",              english: "to have",           tags: ["level2","verb","tener","irregular verb"] },
  { spanish: "ir",                 english: "to go",             tags: ["level2","verb","irregular verb"] },
  { spanish: "tener hambre",       english: "to be hungry",      tags: ["level2","verb","tener"] },
  { spanish: "tener sed",          english: "to be thirsty",     tags: ["level2","verb","tener"] },
  { spanish: "tener frío",         english: "to be cold",        tags: ["level2","verb","tener"] },
  { spanish: "tener calor",        english: "to be hot",         tags: ["level2","verb","tener"] },
  { spanish: "tener prisa",        english: "to be in a hurry",  tags: ["level2","verb","tener"] },
  { spanish: "tener miedo",        english: "to be afraid",      tags: ["level2","verb","tener"] },
  { spanish: "tener sueño",        english: "to be sleepy",      tags: ["level2","verb","tener"] },
  { spanish: "tener ganas de",     english: "to feel like",      tags: ["level2","verb","tener"] },
  { spanish: "tener razón",        english: "to be correct",     tags: ["level2","verb","tener"] },
  { spanish: "tener suerte",       english: "to be lucky",       tags: ["level2","verb","tener"] },
  { spanish: "tener éxito",        english: "to be successful",  tags: ["level2","verb","tener"] },

  // ── Family (individual forms) ────────────────────────────────────────────
  { spanish: "madre",              english: "mother",            tags: ["level2","family"] },
  { spanish: "padre",              english: "father",            tags: ["level2","family"] },
  { spanish: "hijo",               english: "son",               tags: ["level2","family"] },
  { spanish: "hija",               english: "daughter",          tags: ["level2","family"] },
  { spanish: "hermano",            english: "brother",           tags: ["level2","family"] },
  { spanish: "hermana",            english: "sister",            tags: ["level2","family"] },
  { spanish: "tío",                english: "uncle",             tags: ["level2","family"] },
  { spanish: "tía",                english: "aunt",              tags: ["level2","family"] },
  { spanish: "sobrino",            english: "nephew",            tags: ["level2","family"] },
  { spanish: "sobrina",            english: "niece",             tags: ["level2","family"] },
  { spanish: "esposo",             english: "husband",           tags: ["level2","family"] },
  { spanish: "esposa",             english: "wife",              tags: ["level2","family"] },
  { spanish: "abuelo",             english: "grandfather",       tags: ["level2","family"] },
  { spanish: "abuela",             english: "grandmother",       tags: ["level2","family"] },
  { spanish: "bisabuelo",          english: "great grandfather", tags: ["level2","family"] },
  { spanish: "bisabuela",          english: "great grandmother", tags: ["level2","family"] },
  { spanish: "nieto",              english: "grandson",          tags: ["level2","family"] },
  { spanish: "nieta",              english: "granddaughter",     tags: ["level2","family"] },
  { spanish: "suegro",             english: "father-in-law",     tags: ["level2","family"] },
  { spanish: "suegra",             english: "mother-in-law",     tags: ["level2","family"] },
  { spanish: "cuñado",             english: "brother-in-law",    tags: ["level2","family"] },
  { spanish: "cuñada",             english: "sister-in-law",     tags: ["level2","family"] },
  { spanish: "padrastro",          english: "step father",       tags: ["level2","family"] },
  { spanish: "madrastra",          english: "step mother",       tags: ["level2","family"] },
  { spanish: "primo(a)",           english: "cousin",            tags: ["level2","family"] },
  { spanish: "yerno",              english: "son-in-law",        tags: ["level2","family"] },
  { spanish: "nuera",              english: "daughter-in-law",   tags: ["level2","family"] },
  { spanish: "hijastro",           english: "step-son",          tags: ["level2","family"] },
  { spanish: "hijastra",           english: "step-daughter",     tags: ["level2","family"] },
  { spanish: "los parientes",      english: "relatives",         tags: ["level2","family"] },

  // ── La Comida — Carnes y Aves (Meat & Poultry) ───────────────────────
  { spanish: "el ave",             english: "poultry",           tags: ["level2","food","meat"] },
  { spanish: "el bistec",          english: "steak",             tags: ["level2","food","meat"] },
  { spanish: "la carne",           english: "meat",              tags: ["level2","food","meat"] },
  { spanish: "el cerdo",           english: "pork",              tags: ["level2","food","meat"] },
  { spanish: "el puerco",          english: "pork",              tags: ["level2","food","meat"] },
  { spanish: "el cordero",         english: "lamb",              tags: ["level2","food","meat"] },
  { spanish: "la hamburguesa",     english: "hamburger",         tags: ["level2","food","meat"] },
  { spanish: "el huevo",           english: "egg",               tags: ["level2","food","meat"] },
  { spanish: "el jamón",           english: "ham",               tags: ["level2","food","meat"] },
  { spanish: "el pato",            english: "duck",              tags: ["level2","food","meat"] },
  { spanish: "el pavo",            english: "turkey",            tags: ["level2","food","meat"] },
  { spanish: "el pollo",           english: "chicken",           tags: ["level2","food","meat"] },
  { spanish: "la res",             english: "beef",              tags: ["level2","food","meat"] },
  { spanish: "el tocino",          english: "bacon",             tags: ["level2","food","meat"] },
  { spanish: "la tocineta",        english: "bacon",             tags: ["level2","food","meat"] },

  // ── La Comida — Pescado y Mariscos (Seafood) ─────────────────────────
  { spanish: "el atún",            english: "tuna",              tags: ["level2","food","seafood"] },
  { spanish: "el calamar",         english: "squid",             tags: ["level2","food","seafood"] },
  { spanish: "los camarones",      english: "shrimp",            tags: ["level2","food","seafood"] },
  { spanish: "el cangrejo",        english: "crab",              tags: ["level2","food","seafood"] },
  { spanish: "la langosta",        english: "lobster",           tags: ["level2","food","seafood"] },
  { spanish: "los mariscos",       english: "shellfish",         tags: ["level2","food","seafood"] },
  { spanish: "el pescado",         english: "fish",              tags: ["level2","food","seafood"] },

  // ── La Comida — Frutas (Fruit) ────────────────────────────────────────
  { spanish: "el durazno",         english: "peach",             tags: ["level2","food","fruit"] },
  { spanish: "el melocotón",       english: "peach",             tags: ["level2","food","fruit"] },
  { spanish: "la fresa",           english: "strawberry",        tags: ["level2","food","fruit"] },
  { spanish: "el mango",           english: "mango",             tags: ["level2","food","fruit"] },
  { spanish: "la manzana",         english: "apple",             tags: ["level2","food","fruit"] },
  { spanish: "el melón",           english: "cantaloupe",        tags: ["level2","food","fruit"] },
  { spanish: "la naranja",         english: "orange",            tags: ["level2","food","fruit"] },
  { spanish: "la pera",            english: "pear",              tags: ["level2","food","fruit"] },
  { spanish: "el plátano",         english: "banana",            tags: ["level2","food","fruit"] },
  { spanish: "la sandía",          english: "watermelon",        tags: ["level2","food","fruit"] },
  { spanish: "la toronja",         english: "grapefruit",        tags: ["level2","food","fruit"] },
  { spanish: "las uvas",           english: "grapes",            tags: ["level2","food","fruit"] },

  // ── La Comida — Verduras (Vegetables) ────────────────────────────────
  { spanish: "el aguacate",        english: "avocado",           tags: ["level2","food","vegetable"] },
  { spanish: "el ajo",             english: "garlic",            tags: ["level2","food","vegetable"] },
  { spanish: "el apio",            english: "celery",            tags: ["level2","food","vegetable"] },
  { spanish: "la berenjena",       english: "eggplant",          tags: ["level2","food","vegetable"] },
  { spanish: "el brócoli",         english: "broccoli",          tags: ["level2","food","vegetable"] },
  { spanish: "la calabacita",      english: "zucchini",          tags: ["level2","food","vegetable"] },
  { spanish: "la cebolla",         english: "onion",             tags: ["level2","food","vegetable"] },
  { spanish: "el chile",           english: "chili pepper",      tags: ["level2","food","vegetable"] },
  { spanish: "los chícharos",      english: "peas",              tags: ["level2","food","vegetable"] },
  { spanish: "los champiñones",    english: "mushrooms",         tags: ["level2","food","vegetable"] },
  { spanish: "la coliflor",        english: "cauliflower",       tags: ["level2","food","vegetable"] },
  { spanish: "la col",             english: "cabbage",           tags: ["level2","food","vegetable"] },
  { spanish: "los ejotes",         english: "green beans",       tags: ["level2","food","vegetable"] },
  { spanish: "las espinacas",      english: "spinach",           tags: ["level2","food","vegetable"] },
  { spanish: "la lechuga",         english: "lettuce",           tags: ["level2","food","vegetable"] },
  { spanish: "el maíz",            english: "corn",              tags: ["level2","food","vegetable"] },
  { spanish: "la papa",            english: "potato",            tags: ["level2","food","vegetable"] },
  { spanish: "el pepino",          english: "cucumber",          tags: ["level2","food","vegetable"] },
  { spanish: "el tomate",          english: "tomato",            tags: ["level2","food","vegetable"] },
  { spanish: "el jitomate",        english: "tomato",            tags: ["level2","food","vegetable"] },
  { spanish: "la zanahoria",       english: "carrot",            tags: ["level2","food","vegetable"] },

  // ── La Comida — Productos Lácteos (Dairy) ────────────────────────────
  { spanish: "la crema",           english: "cream",             tags: ["level2","food","dairy"] },
  { spanish: "la leche",           english: "milk",              tags: ["level2","food","dairy"] },
  { spanish: "el queso",           english: "cheese",            tags: ["level2","food","dairy"] },
  { spanish: "el yogurt",          english: "yogurt",            tags: ["level2","food","dairy"] },
  { spanish: "la mantequilla",     english: "butter",            tags: ["level2","food","dairy"] },

  // ── La Comida — Bebidas (Drinks) ──────────────────────────────────────
  { spanish: "el agua",            english: "water",             tags: ["level2","food","drink"] },
  { spanish: "el café",            english: "coffee",            tags: ["level2","food","drink"] },
  { spanish: "la cerveza",         english: "beer",              tags: ["level2","food","drink"] },
  { spanish: "el jugo",            english: "juice",             tags: ["level2","food","drink"] },
  { spanish: "el refresco",        english: "soft drink",        tags: ["level2","food","drink"] },
  { spanish: "el té",              english: "tea",               tags: ["level2","food","drink"] },
  { spanish: "el vino",            english: "wine",              tags: ["level2","food","drink"] },

  // ── La Comida — Postres (Desserts) ────────────────────────────────────
  { spanish: "el dulce",           english: "candy; sweet",      tags: ["level2","food","dessert"] },
  { spanish: "la galleta",         english: "cookie",            tags: ["level2","food","dessert"] },
  { spanish: "el helado",          english: "ice cream",         tags: ["level2","food","dessert"] },
  { spanish: "el pay",             english: "pie",               tags: ["level2","food","dessert"] },
  { spanish: "el pastel",          english: "cake",              tags: ["level2","food","dessert"] },

  // ── La Comida — Otras Cosas Importantes (Pantry) ─────────────────────
  { spanish: "el aceite",          english: "oil",               tags: ["level2","food","pantry"] },
  { spanish: "el aceite de oliva", english: "olive oil",         tags: ["level2","food","pantry"] },
  { spanish: "el arroz",           english: "rice",              tags: ["level2","food","pantry"] },
  { spanish: "el azúcar",          english: "sugar",             tags: ["level2","food","pantry"] },
  { spanish: "los frijoles",       english: "beans",             tags: ["level2","food","pantry"] },
  { spanish: "la harina",          english: "flour",             tags: ["level2","food","pantry"] },
  { spanish: "la mayonesa",        english: "mayonnaise",        tags: ["level2","food","pantry"] },
  { spanish: "la miel",            english: "honey",             tags: ["level2","food","pantry"] },
  { spanish: "las nueces",         english: "nuts",              tags: ["level2","food","pantry"] },
  { spanish: "el pan",             english: "bread",             tags: ["level2","food","pantry"] },
  { spanish: "la pimienta",        english: "pepper",            tags: ["level2","food","pantry"] },
  { spanish: "la sal",             english: "salt",              tags: ["level2","food","pantry"] },

  // ── Frases Preposicionales (Prepositional Phrases) ────────────────────
  { spanish: "a",                  english: "to",                tags: ["level2","preposition"] },
  { spanish: "a la derecha de",    english: "to the right of",   tags: ["level2","preposition"] },
  { spanish: "a la izquierda de",  english: "to the left of",    tags: ["level2","preposition"] },
  { spanish: "arriba de",          english: "above",             tags: ["level2","preposition"] },
  { spanish: "abajo de",           english: "under",             tags: ["level2","preposition"] },
  { spanish: "debajo de",          english: "under; below",      tags: ["level2","preposition"] },
  { spanish: "al lado de",         english: "next to; beside",   tags: ["level2","preposition"] },
  { spanish: "junto a",            english: "next to",           tags: ["level2","preposition"] },
  { spanish: "atrás de",           english: "behind",            tags: ["level2","preposition"] },
  { spanish: "detrás de",          english: "behind",            tags: ["level2","preposition"] },
  { spanish: "cerca de",           english: "near",              tags: ["level2","preposition"] },
  { spanish: "dentro de",          english: "inside of",         tags: ["level2","preposition"] },
  { spanish: "en",                 english: "in; on; at",        tags: ["level2","preposition"] },
  { spanish: "encima de",          english: "on top of",         tags: ["level2","preposition"] },
  { spanish: "sobre",              english: "on",                tags: ["level2","preposition"] },
  { spanish: "enfrente de",        english: "facing; across from; in front of", tags: ["level2","preposition"] },
  { spanish: "entre",              english: "between",           tags: ["level2","preposition"] },
  { spanish: "fuera de",           english: "outside of",        tags: ["level2","preposition"] },
  { spanish: "lejos de",           english: "far from",          tags: ["level2","preposition"] },

  // ── El Clima — Estaciones (Seasons) ──────────────────────────────────
  { spanish: "la primavera",       english: "spring",            tags: ["level2","weather","season"] },
  { spanish: "el verano",          english: "summer",            tags: ["level2","weather","season"] },
  { spanish: "el otoño",           english: "fall",              tags: ["level2","weather","season"] },
  { spanish: "el invierno",        english: "winter",            tags: ["level2","weather","season"] },

  // ── El Clima — Expresiones con Hacer ─────────────────────────────────
  { spanish: "hace fresco",        english: "it's cool",         tags: ["level2","weather"] },
  { spanish: "hace frío",          english: "it's cold",         tags: ["level2","weather"] },
  { spanish: "hace calor",         english: "it's hot",          tags: ["level2","weather"] },
  { spanish: "hace buen tiempo",   english: "it's a nice day",   tags: ["level2","weather"] },
  { spanish: "hace mal tiempo",    english: "it's not a nice day", tags: ["level2","weather"] },
  { spanish: "hace viento",        english: "it's windy",        tags: ["level2","weather"] },
  { spanish: "hace sol",           english: "it's sunny",        tags: ["level2","weather"] },

  // ── El Clima — Expresiones con Estar ─────────────────────────────────
  { spanish: "está lloviendo",     english: "it's raining",      tags: ["level2","weather"] },
  { spanish: "está nevando",       english: "it's snowing",      tags: ["level2","weather"] },
  { spanish: "está despejado",     english: "the sky is clear",  tags: ["level2","weather"] },
  { spanish: "está nublado",       english: "it's cloudy",       tags: ["level2","weather"] },
  { spanish: "está parcialmente nublado", english: "it's partly cloudy", tags: ["level2","weather"] },
  { spanish: "está soleado",       english: "it's sunny",        tags: ["level2","weather"] },

  // ── El Clima — Tiempo Futuro (Future Weather) ─────────────────────────
  { spanish: "va a llover",        english: "it's going to rain",    tags: ["level2","weather"] },
  { spanish: "va a nevar",         english: "it's going to snow",    tags: ["level2","weather"] },
  { spanish: "va a hacer buen tiempo", english: "it's going to be a nice day", tags: ["level2","weather"] },
  { spanish: "va a hacer frío",    english: "it's going to be cold", tags: ["level2","weather"] },

  // ── El Clima — Clima Extremo (Extreme Weather) ────────────────────────
  { spanish: "el granizo",         english: "hail",              tags: ["level2","weather","extreme weather"] },
  { spanish: "el huracán",         english: "hurricane",         tags: ["level2","weather","extreme weather"] },
  { spanish: "la inundación",      english: "flood",             tags: ["level2","weather","extreme weather"] },
  { spanish: "el relámpago",       english: "lightning",         tags: ["level2","weather","extreme weather"] },
  { spanish: "la tormenta",        english: "storm",             tags: ["level2","weather","extreme weather"] },
  { spanish: "la tormenta de nieve", english: "snow storm",      tags: ["level2","weather","extreme weather"] },
  { spanish: "el tornado",         english: "tornado",           tags: ["level2","weather","extreme weather"] },
  { spanish: "el trueno",          english: "thunder",           tags: ["level2","weather","extreme weather"] },
  { spanish: "Está granizando",    english: "it is hailing",     tags: ["level2","weather","extreme weather"] },
  { spanish: "Hay un huracán",     english: "there is a hurricane",   tags: ["level2","weather","extreme weather"] },
  { spanish: "Hay una inundación", english: "there is a flood",       tags: ["level2","weather","extreme weather"] },
  { spanish: "Hay relámpagos",     english: "there is lightning",     tags: ["level2","weather","extreme weather"] },
  { spanish: "Hay una tormenta",   english: "there is a storm",       tags: ["level2","weather","extreme weather"] },
  { spanish: "Hay una tormenta de nieve", english: "there is a snow storm", tags: ["level2","weather","extreme weather"] },
  { spanish: "Hay un tornado",     english: "there is a tornado",     tags: ["level2","weather","extreme weather"] },
  { spanish: "Hay truenos",        english: "there is thunder",       tags: ["level2","weather","extreme weather"] },

  // ── Verbos como Gustar (Gustar-like Verbs) ────────────────────────────
  { spanish: "caer bien",          english: "to like someone",           tags: ["level2","verb","gustar"] },
  { spanish: "caer mal",           english: "to dislike someone",        tags: ["level2","verb","gustar"] },
  { spanish: "dar igual",          english: "to not care either way",    tags: ["level2","verb","gustar"] },
  { spanish: "doler",              english: "to hurt",                   tags: ["level2","verb","gustar"] },
  { spanish: "encantar",           english: "to love (something)",       tags: ["level2","verb","gustar"] },
  { spanish: "fascinar",           english: "to fascinate",              tags: ["level2","verb","gustar"] },
  { spanish: "fastidiar",          english: "to annoy",                  tags: ["level2","verb","gustar"] },
  { spanish: "hacer falta",        english: "to need; to lack",          tags: ["level2","verb","gustar"] },
  { spanish: "importar",           english: "to be important to",        tags: ["level2","verb","gustar"] },
  { spanish: "interesar",          english: "to interest",               tags: ["level2","verb","gustar"] },
  { spanish: "molestar",           english: "to bother",                 tags: ["level2","verb","gustar"] },
  { spanish: "parecer",            english: "to seem",                   tags: ["level2","verb","gustar"] },
  { spanish: "preocupar",          english: "to worry",                  tags: ["level2","verb","gustar"] },
  { spanish: "quedar",             english: "to have (any amount) left", tags: ["level2","verb","gustar"] },
  { spanish: "quedar bien",        english: "to look good on someone (clothing)", tags: ["level2","verb","gustar"] },
  { spanish: "quedar mal",         english: "to look bad on someone (clothing)",  tags: ["level2","verb","gustar"] },

  // ── Verbos Reflexivos (Reflexive Verbs) ───────────────────────────────
  { spanish: "acordarse (de)",     english: "to remember",               tags: ["level2","verb","reflexive"] },
  { spanish: "acostarse",          english: "to go to bed",              tags: ["level2","verb","reflexive"] },
  { spanish: "afeitarse",          english: "to shave",                  tags: ["level2","verb","reflexive"] },
  { spanish: "alegrarse",          english: "to be happy; to become glad", tags: ["level2","verb","reflexive"] },
  { spanish: "arrepentirse",       english: "to repent",                 tags: ["level2","verb","reflexive"] },
  { spanish: "bañarse",            english: "to bathe",                  tags: ["level2","verb","reflexive"] },
  { spanish: "cansarse",           english: "to get tired",              tags: ["level2","verb","reflexive"] },
  { spanish: "caerse",             english: "to fall down",              tags: ["level2","verb","reflexive"] },
  { spanish: "cepillarse",         english: "to brush",                  tags: ["level2","verb","reflexive"] },
  { spanish: "cortarse el pelo",   english: "to get a hair cut",         tags: ["level2","verb","reflexive"] },
  { spanish: "darse prisa",        english: "to hurry",                  tags: ["level2","verb","reflexive"] },
  { spanish: "ducharse",           english: "to shower",                 tags: ["level2","verb","reflexive"] },
  { spanish: "despertarse",        english: "to wake up",                tags: ["level2","verb","reflexive"] },
  { spanish: "desvestirse",        english: "to undress",                tags: ["level2","verb","reflexive"] },
  { spanish: "divertirse",         english: "to have fun",               tags: ["level2","verb","reflexive"] },
  { spanish: "dormirse",           english: "to fall asleep",            tags: ["level2","verb","reflexive"] },
  { spanish: "enojarse",           english: "to get angry",              tags: ["level2","verb","reflexive"] },
  { spanish: "enfadarse",          english: "to get angry",              tags: ["level2","verb","reflexive"] },
  { spanish: "irse",               english: "to leave",                  tags: ["level2","verb","reflexive"] },
  { spanish: "lavarse",            english: "to wash (oneself)",         tags: ["level2","verb","reflexive"] },
  { spanish: "levantarse",         english: "to get up",                 tags: ["level2","verb","reflexive"] },
  { spanish: "maquillarse",        english: "to put on make-up",         tags: ["level2","verb","reflexive"] },
  { spanish: "pararse",            english: "to stand up",               tags: ["level2","verb","reflexive"] },
  { spanish: "peinarse",           english: "to comb",                   tags: ["level2","verb","reflexive"] },
  { spanish: "ponerse",            english: "to put on (clothing)",      tags: ["level2","verb","reflexive"] },
  { spanish: "preocuparse",        english: "to be worried",             tags: ["level2","verb","reflexive"] },
  { spanish: "quedarse",           english: "to stay; to remain",        tags: ["level2","verb","reflexive"] },
  { spanish: "quejarse",           english: "to complain",               tags: ["level2","verb","reflexive"] },
  { spanish: "quitarse",           english: "to take off (clothing)",    tags: ["level2","verb","reflexive"] },
  { spanish: "reírse",             english: "to laugh",                  tags: ["level2","verb","reflexive"] },
  { spanish: "secarse",            english: "to dry (oneself)",          tags: ["level2","verb","reflexive"] },
  { spanish: "sentarse",           english: "to sit down",               tags: ["level2","verb","reflexive"] },
  { spanish: "sentirse",           english: "to feel",                   tags: ["level2","verb","reflexive"] },
  { spanish: "sonreírse",          english: "to smile",                  tags: ["level2","verb","reflexive"] },
  { spanish: "vestirse",           english: "to get dressed",            tags: ["level2","verb","reflexive"] },

  // ── Los Pasatiempos (Hobbies) — III-19 ───────────────────────────────
  { spanish: "andar en bicicleta", english: "to bike",                   tags: ["level3","hobby"] },
  { spanish: "bordar",             english: "to do needlepoint",         tags: ["level3","hobby"] },
  { spanish: "acampar",            english: "to camp",                   tags: ["level3","hobby"] },
  { spanish: "coleccionar",        english: "to collect",                tags: ["level3","hobby"] },
  { spanish: "coser",              english: "to sew",                    tags: ["level3","hobby"] },
  { spanish: "dibujar",            english: "to draw",                   tags: ["level3","hobby"] },
  { spanish: "hacer ejercicio",    english: "to exercise",               tags: ["level3","hobby"] },
  { spanish: "jugar al golf",      english: "to play golf",              tags: ["level3","hobby"] },
  { spanish: "jugar al tenis",     english: "to play tennis",            tags: ["level3","hobby"] },
  { spanish: "jugar cartas",       english: "to play cards",             tags: ["level3","hobby"] },
  { spanish: "navegar en internet",english: "to surf the net",           tags: ["level3","hobby"] },
  { spanish: "pasear",             english: "to go for a walk",          tags: ["level3","hobby"] },
  { spanish: "pintar",             english: "to paint",                  tags: ["level3","hobby"] },
  { spanish: "sacar fotos",        english: "to take photos",            tags: ["level3","hobby"] },
  { spanish: "tejer",              english: "to knit",                   tags: ["level3","hobby"] },
  { spanish: "tocar un instrumento", english: "to play an instrument",   tags: ["level3","hobby"] },
  { spanish: "ver la televisión",  english: "to watch television",       tags: ["level3","hobby"] },
  { spanish: "ir a acampar",       english: "to go camping",             tags: ["level3","hobby"] },
  { spanish: "ir a la playa",      english: "to go to the beach",        tags: ["level3","hobby"] },
  { spanish: "ir al cine",         english: "to go to the movies",       tags: ["level3","hobby"] },
  { spanish: "ir de compras",      english: "to go shopping",            tags: ["level3","hobby"] },
  { spanish: "ir de excursión",    english: "to go hiking",              tags: ["level3","hobby"] },
  { spanish: "ir de pesca",        english: "to go fishing",             tags: ["level3","hobby"] },
];

async function seedIfEmpty() {
  const seeded = await DB.getSetting('seeded');
  if (seeded === 'v12') return;

  const existing = await DB.getAllCards();
  const existingBySpanish = new Map(existing.map(c => [c.spanish.toLowerCase(), c]));

  for (const seed of SEED_CARDS) {
    const key = seed.spanish.toLowerCase();
    if (existingBySpanish.has(key)) {
      const card = existingBySpanish.get(key);
      await DB.updateCard(card.id, { tags: seed.tags });
    } else {
      await DB.createCard({ ...seed, notes: '' });
    }
  }

  await DB.setSetting('seeded', 'v12');
  console.log('Seed v12 complete.');
}

window.seedIfEmpty = seedIfEmpty;
