const SEED_CARDS = [
  // ── Regular Verbs (-AR) ──────────────────────────────────────────────
  { spanish: "aceptar",    english: "to accept",        tags: ["level1","verb"] },
  { spanish: "bailar",     english: "to dance",          tags: ["level1","verb"] },
  { spanish: "bajar",      english: "to go down",        tags: ["level1","verb"] },
  { spanish: "buscar",     english: "to search for",     tags: ["level1","verb"] },
  { spanish: "caminar",    english: "to walk",           tags: ["level1","verb"] },
  { spanish: "cantar",     english: "to sing",           tags: ["level1","verb"] },
  { spanish: "cocinar",    english: "to cook",           tags: ["level1","verb"] },
  { spanish: "comprar",    english: "to buy",            tags: ["level1","verb"] },
  { spanish: "contestar",  english: "to answer",         tags: ["level1","verb"] },
  { spanish: "cortar",     english: "to cut",            tags: ["level1","verb"] },
  { spanish: "enseñar",    english: "to teach",          tags: ["level1","verb"] },
  { spanish: "entrar",     english: "to enter",          tags: ["level1","verb"] },
  { spanish: "enviar",     english: "to send",           tags: ["level1","verb"] },
  { spanish: "escuchar",   english: "to listen",         tags: ["level1","verb"] },
  { spanish: "estudiar",   english: "to study",          tags: ["level1","verb"] },
  { spanish: "gastar",     english: "to spend",          tags: ["level1","verb"] },
  { spanish: "hablar",     english: "to speak",          tags: ["level1","verb"] },
  { spanish: "lavar",      english: "to wash",           tags: ["level1","verb"] },
  { spanish: "levantar",   english: "to lift",           tags: ["level1","verb"] },
  { spanish: "limpiar",    english: "to clean",          tags: ["level1","verb"] },
  { spanish: "llegar",     english: "to arrive",         tags: ["level1","verb"] },
  { spanish: "llevar",     english: "to carry",          tags: ["level1","verb"] },
  { spanish: "llorar",     english: "to cry",            tags: ["level1","verb"] },
  { spanish: "mandar",     english: "to send",           tags: ["level1","verb"] },
  { spanish: "manejar",    english: "to drive",          tags: ["level1","verb"] },
  { spanish: "nadar",      english: "to swim",           tags: ["level1","verb"] },
  { spanish: "necesitar",  english: "to need",           tags: ["level1","verb"] },
  { spanish: "practicar",  english: "to practice",       tags: ["level1","verb"] },
  { spanish: "preparar",   english: "to prepare",        tags: ["level1","verb"] },
  { spanish: "regresar",   english: "to return",         tags: ["level1","verb"] },
  { spanish: "terminar",   english: "to finish",         tags: ["level1","verb"] },
  { spanish: "tomar",      english: "to take",           tags: ["level1","verb"] },
  { spanish: "trabajar",   english: "to work",           tags: ["level1","verb"] },
  { spanish: "usar",       english: "to use",            tags: ["level1","verb"] },
  { spanish: "viajar",     english: "to travel",         tags: ["level1","verb"] },
  // ── Regular Verbs (-ER) ──────────────────────────────────────────────
  { spanish: "aprender",   english: "to learn",          tags: ["level1","verb"] },
  { spanish: "beber",      english: "to drink",          tags: ["level1","verb"] },
  { spanish: "comer",      english: "to eat",            tags: ["level1","verb"] },
  { spanish: "comprender", english: "to understand",     tags: ["level1","verb"] },
  { spanish: "correr",     english: "to run",            tags: ["level1","verb"] },
  { spanish: "creer",      english: "to think",          tags: ["level1","verb"] },
  { spanish: "deber",      english: "ought to",          tags: ["level1","verb"] },
  { spanish: "leer",       english: "to read",           tags: ["level1","verb"] },
  { spanish: "prometer",   english: "to promise",        tags: ["level1","verb"] },
  { spanish: "responder",  english: "to respond",        tags: ["level1","verb"] },
  { spanish: "temer",      english: "to fear",           tags: ["level1","verb"] },
  { spanish: "vender",     english: "to sell",           tags: ["level1","verb"] },
  // ── Regular Verbs (-IR) ──────────────────────────────────────────────
  { spanish: "abrir",      english: "to open",           tags: ["level1","verb"] },
  { spanish: "asistir",    english: "to attend",         tags: ["level1","verb"] },
  { spanish: "decidir",    english: "to decide",         tags: ["level1","verb"] },
  { spanish: "discutir",   english: "to argue",          tags: ["level1","verb"] },
  { spanish: "escribir",   english: "to write",          tags: ["level1","verb"] },
  { spanish: "recibir",    english: "to receive",        tags: ["level1","verb"] },
  { spanish: "subir",      english: "to go up",          tags: ["level1","verb"] },
  { spanish: "vivir",      english: "to live",           tags: ["level1","verb"] },
  // ── La Casa — Bedroom ────────────────────────────────────────────────
  { spanish: "la almohada",        english: "pillow",           tags: ["level1","house"] },
  { spanish: "la cama",            english: "bed",              tags: ["level1","house"] },
  { spanish: "el closet",          english: "closet",           tags: ["level1","house"] },
  { spanish: "la cómoda",          english: "dresser",          tags: ["level1","house"] },
  { spanish: "la mesita de noche", english: "night table",      tags: ["level1","house"] },
  // ── La Casa — Bathroom ───────────────────────────────────────────────
  { spanish: "la bañera",          english: "bathtub",          tags: ["level1","house"] },
  { spanish: "la ducha",           english: "shower",           tags: ["level1","house"] },
  { spanish: "el espejo",          english: "mirror",           tags: ["level1","house"] },
  { spanish: "el jabón",           english: "soap",             tags: ["level1","house"] },
  { spanish: "el lavamanos",       english: "sink",             tags: ["level1","house"] },
  { spanish: "el retrete",         english: "toilet",           tags: ["level1","house"] },
  // ── La Casa — Kitchen ────────────────────────────────────────────────
  { spanish: "la alacena",         english: "cupboard",         tags: ["level1","house"] },
  { spanish: "el basurero",        english: "garbage can",      tags: ["level1","house"] },
  { spanish: "la cafetera",        english: "coffee maker",     tags: ["level1","house"] },
  { spanish: "el congelador",      english: "freezer",          tags: ["level1","house"] },
  { spanish: "la escoba",          english: "broom",            tags: ["level1","house"] },
  { spanish: "la estufa",          english: "stove",            tags: ["level1","house"] },
  { spanish: "el fregadero",       english: "sink",             tags: ["level1","house"] },
  { spanish: "el horno",           english: "oven",             tags: ["level1","house"] },
  { spanish: "el lavaplatos",      english: "dishwasher",       tags: ["level1","house"] },
  { spanish: "la llave",           english: "faucet",           tags: ["level1","house"] },
  { spanish: "el microondas",      english: "microwave",        tags: ["level1","house"] },
  { spanish: "las ollas",          english: "pots",             tags: ["level1","house"] },
  { spanish: "el refrigerador",    english: "refrigerator",     tags: ["level1","house"] },
  { spanish: "los sartenes",       english: "pans",             tags: ["level1","house"] },
  { spanish: "el tostador",        english: "toaster",          tags: ["level1","house"] },
  { spanish: "el trapeador",       english: "mop",              tags: ["level1","house"] },
  // ── La Casa — Living Room ────────────────────────────────────────────
  { spanish: "la alfombra",        english: "carpet",           tags: ["level1","house"] },
  { spanish: "la chimenea",        english: "fireplace",        tags: ["level1","house"] },
  { spanish: "el cuadro",          english: "picture",          tags: ["level1","house"] },
  { spanish: "el estéreo",         english: "stereo",           tags: ["level1","house"] },
  { spanish: "la lámpara",         english: "lamp",             tags: ["level1","house"] },
  { spanish: "el librero",         english: "bookcase",         tags: ["level1","house"] },
  { spanish: "la mesa de centro",  english: "coffee table",     tags: ["level1","house"] },
  { spanish: "el reloj",           english: "clock",            tags: ["level1","house"] },
  { spanish: "la repisa",          english: "shelf",            tags: ["level1","house"] },
  { spanish: "la contestadora",    english: "answering machine", tags: ["level1","house"] },
  { spanish: "el sillón",          english: "armchair",         tags: ["level1","house"] },
  { spanish: "el sofá",            english: "sofa",             tags: ["level1","house"] },
  { spanish: "el teléfono",        english: "telephone",        tags: ["level1","house"] },
  { spanish: "la televisión",      english: "tv",               tags: ["level1","house"] },
  // ── La Casa — Dining Room ────────────────────────────────────────────
  { spanish: "los cubiertos",      english: "silverware",       tags: ["level1","house"] },
  { spanish: "la cuchara",         english: "soup spoon",       tags: ["level1","house"] },
  { spanish: "la cucharita",       english: "teaspoon",         tags: ["level1","house"] },
  { spanish: "el cuchillo",        english: "knife",            tags: ["level1","house"] },
  { spanish: "la mesa",            english: "table",            tags: ["level1","house"] },
  { spanish: "el plato",           english: "plate",            tags: ["level1","house"] },
  { spanish: "la silla",           english: "chair",            tags: ["level1","house"] },
  { spanish: "la servilleta",      english: "napkin",           tags: ["level1","house"] },
  { spanish: "la taza",            english: "cup",              tags: ["level1","house"] },
  { spanish: "el tazón",           english: "bowl",             tags: ["level1","house"] },
  { spanish: "el tenedor",         english: "fork",             tags: ["level1","house"] },
  { spanish: "el vaso",            english: "glass",            tags: ["level1","house"] },
  // ── La Casa — General ────────────────────────────────────────────────
  { spanish: "el ático",           english: "attic",            tags: ["level1","house"] },
  { spanish: "la computadora",     english: "computer",         tags: ["level1","house"] },
  { spanish: "las cortinas",       english: "curtains",         tags: ["level1","house"] },
  { spanish: "la escalera",        english: "staircase",        tags: ["level1","house"] },
  { spanish: "el escritorio",      english: "desk",             tags: ["level1","house"] },
  { spanish: "la flor",            english: "flower",           tags: ["level1","house"] },
  { spanish: "el florero",         english: "vase",             tags: ["level1","house"] },
  { spanish: "el foco",            english: "light bulb",       tags: ["level1","house"] },
  { spanish: "el garaje",          english: "garage",           tags: ["level1","house"] },
  { spanish: "el jardín",          english: "garden",           tags: ["level1","house"] },
  { spanish: "la lavadora",        english: "washing machine",  tags: ["level1","house"] },
  { spanish: "la luz",             english: "light",            tags: ["level1","house"] },
  { spanish: "la oficina",         english: "office",           tags: ["level1","house"] },
  { spanish: "la pared",           english: "wall",             tags: ["level1","house"] },
  { spanish: "las persianas",      english: "shades",           tags: ["level1","house"] },
  { spanish: "el primer piso",     english: "first floor",      tags: ["level1","house"] },
  { spanish: "los productos de limpieza", english: "cleaning products", tags: ["level1","house"] },
  { spanish: "la puerta",          english: "door",             tags: ["level1","house"] },
  { spanish: "la secadora",        english: "dryer",            tags: ["level1","house"] },
  { spanish: "el segundo piso",    english: "second floor",     tags: ["level1","house"] },
  { spanish: "el sótano",          english: "basement",         tags: ["level1","house"] },
  { spanish: "el suelo",           english: "floor",            tags: ["level1","house"] },
  { spanish: "el techo",           english: "ceiling",          tags: ["level1","house"] },
  { spanish: "la ventana",         english: "window",           tags: ["level1","house"] },
  { spanish: "el ventilador",      english: "fan",              tags: ["level1","house"] },
  // ── Clothing ─────────────────────────────────────────────────────────
  { spanish: "el abrigo",          english: "coat",             tags: ["level1","clothing"] },
  { spanish: "la cartera",         english: "purse",            tags: ["level1","clothing"] },
  { spanish: "la billetera",       english: "wallet",           tags: ["level1","clothing"] },
  { spanish: "el cinturón",        english: "belt",             tags: ["level1","clothing"] },
  { spanish: "el paraguas",        english: "umbrella",         tags: ["level1","clothing"] },
  { spanish: "el sombrero",        english: "hat",              tags: ["level1","clothing"] },
  { spanish: "el suéter",          english: "sweater",          tags: ["level1","clothing"] },
  { spanish: "el traje",           english: "suit",             tags: ["level1","clothing"] },
  { spanish: "el traje de baño",   english: "bathing suit",     tags: ["level1","clothing"] },
  { spanish: "el vestido",         english: "dress",            tags: ["level1","clothing"] },
  { spanish: "el zapato",          english: "shoe",             tags: ["level1","clothing"] },
  { spanish: "la blusa",           english: "blouse",           tags: ["level1","clothing"] },
  { spanish: "la camisa",          english: "shirt",            tags: ["level1","clothing"] },
  { spanish: "la camiseta",        english: "t-shirt",          tags: ["level1","clothing"] },
  { spanish: "la chaqueta",        english: "jacket",           tags: ["level1","clothing"] },
  { spanish: "la corbata",         english: "tie",              tags: ["level1","clothing"] },
  { spanish: "la falda",           english: "skirt",            tags: ["level1","clothing"] },
  { spanish: "la gorra",           english: "cap",              tags: ["level1","clothing"] },
  { spanish: "las botas",          english: "boots",            tags: ["level1","clothing"] },
  { spanish: "las sandalias",      english: "sandals",          tags: ["level1","clothing"] },
  { spanish: "los calcetines",     english: "socks",            tags: ["level1","clothing"] },
  { spanish: "los jeans",          english: "jeans",            tags: ["level1","clothing"] },
  { spanish: "los pantalones",     english: "pants",            tags: ["level1","clothing"] },
  { spanish: "las bermudas",       english: "shorts",           tags: ["level1","clothing"] },
  { spanish: "los tenis",          english: "sneakers",         tags: ["level1","clothing"] },
  { spanish: "la pijama",          english: "pajama",           tags: ["level1","clothing"] },
  { spanish: "el brasiere",        english: "bra",              tags: ["level1","clothing"] },
  { spanish: "los calzones",       english: "women's underwear", tags: ["level1","clothing"] },
  { spanish: "los calzoncillos",   english: "men's underwear",  tags: ["level1","clothing"] },
  { spanish: "la bufanda",         english: "scarf",            tags: ["level1","clothing"] },
  { spanish: "los guantes",        english: "gloves",           tags: ["level1","clothing"] },
  { spanish: "el saco",            english: "sport jacket",     tags: ["level1","clothing"] },
  { spanish: "el chaleco",         english: "vest",             tags: ["level1","clothing"] },
  // ── Numbers ───────────────────────────────────────────────────────────
  { spanish: "cero",               english: "0, zero",          tags: ["level1","number"] },
  { spanish: "uno",                english: "1, one",           tags: ["level1","number"] },
  { spanish: "dos",                english: "2, two",           tags: ["level1","number"] },
  { spanish: "tres",               english: "3, three",         tags: ["level1","number"] },
  { spanish: "cuatro",             english: "4, four",          tags: ["level1","number"] },
  { spanish: "cinco",              english: "5, five",          tags: ["level1","number"] },
  { spanish: "seis",               english: "6, six",           tags: ["level1","number"] },
  { spanish: "siete",              english: "7, seven",         tags: ["level1","number"] },
  { spanish: "ocho",               english: "8, eight",         tags: ["level1","number"] },
  { spanish: "nueve",              english: "9, nine",          tags: ["level1","number"] },
  { spanish: "diez",               english: "10, ten",          tags: ["level1","number"] },
  { spanish: "once",               english: "11, eleven",       tags: ["level1","number"] },
  { spanish: "doce",               english: "12, twelve",       tags: ["level1","number"] },
  { spanish: "trece",              english: "13, thirteen",     tags: ["level1","number"] },
  { spanish: "catorce",            english: "14, fourteen",     tags: ["level1","number"] },
  { spanish: "quince",             english: "15, fifteen",      tags: ["level1","number"] },
  { spanish: "dieciséis",          english: "16, sixteen",      tags: ["level1","number"] },
  { spanish: "diecisiete",         english: "17, seventeen",    tags: ["level1","number"] },
  { spanish: "dieciocho",          english: "18, eighteen",     tags: ["level1","number"] },
  { spanish: "diecinueve",         english: "19, nineteen",     tags: ["level1","number"] },
  { spanish: "veinte",             english: "20, twenty",       tags: ["level1","number"] },
  { spanish: "veintiuno",          english: "21, twenty-one",   tags: ["level1","number"] },
  { spanish: "veintidós",          english: "22, twenty-two",   tags: ["level1","number"] },
  { spanish: "veintitrés",         english: "23, twenty-three", tags: ["level1","number"] },
  { spanish: "veinticuatro",       english: "24, twenty-four",  tags: ["level1","number"] },
  { spanish: "veinticinco",        english: "25, twenty-five",  tags: ["level1","number"] },
  { spanish: "veintiséis",         english: "26, twenty-six",   tags: ["level1","number"] },
  { spanish: "veintisiete",        english: "27, twenty-seven", tags: ["level1","number"] },
  { spanish: "veintiocho",         english: "28, twenty-eight", tags: ["level1","number"] },
  { spanish: "veintinueve",        english: "29, twenty-nine",  tags: ["level1","number"] },
  { spanish: "treinta",            english: "30, thirty",       tags: ["level1","number"] },
  { spanish: "treinta y uno",      english: "31, thirty-one",   tags: ["level1","number"] },
  { spanish: "treinta y dos",      english: "32, thirty-two",   tags: ["level1","number"] },
  { spanish: "treinta y tres",     english: "33, thirty-three", tags: ["level1","number"] },
  { spanish: "treinta y cuatro",   english: "34, thirty-four",  tags: ["level1","number"] },
  { spanish: "treinta y cinco",    english: "35, thirty-five",  tags: ["level1","number"] },
  { spanish: "treinta y seis",     english: "36, thirty-six",   tags: ["level1","number"] },
  { spanish: "treinta y siete",    english: "37, thirty-seven", tags: ["level1","number"] },
  { spanish: "treinta y ocho",     english: "38, thirty-eight", tags: ["level1","number"] },
  { spanish: "treinta y nueve",    english: "39, thirty-nine",  tags: ["level1","number"] },
  { spanish: "cuarenta",           english: "40, forty",        tags: ["level1","number"] },
  { spanish: "cincuenta",          english: "50, fifty",        tags: ["level1","number"] },
  { spanish: "sesenta",            english: "60, sixty",        tags: ["level1","number"] },
  { spanish: "setenta",            english: "70, seventy",      tags: ["level1","number"] },
  { spanish: "ochenta",            english: "80, eighty",       tags: ["level1","number"] },
  { spanish: "noventa",            english: "90, ninety",       tags: ["level1","number"] },
  { spanish: "cien",               english: "100, one hundred", tags: ["level1","number"] },
  // ── Professions ───────────────────────────────────────────────────────
  { spanish: "abogado(a)",         english: "lawyer",           tags: ["level1","profession"] },
  { spanish: "actor/actriz",       english: "actor/actress",    tags: ["level1","profession"] },
  { spanish: "agente inmobiliario",english: "real estate agent", tags: ["level1","profession"] },
  { spanish: "ama de casa",        english: "housewife",        tags: ["level1","profession"] },
  { spanish: "arquitecto(a)",      english: "architect",        tags: ["level1","profession"] },
  { spanish: "cantante",           english: "singer",           tags: ["level1","profession"] },
  { spanish: "contador(a)",        english: "accountant",       tags: ["level1","profession"] },
  { spanish: "dentista",           english: "dentist",          tags: ["level1","profession"] },
  { spanish: "doctor(a)",          english: "doctor",           tags: ["level1","profession"] },
  { spanish: "enfermero(a)",       english: "nurse",            tags: ["level1","profession"] },
  { spanish: "escritor(a)",        english: "writer",           tags: ["level1","profession"] },
  { spanish: "gerente",            english: "manager",          tags: ["level1","profession"] },
  { spanish: "ingeniero(a)",       english: "engineer",         tags: ["level1","profession"] },
  { spanish: "maestro(a)",         english: "teacher",          tags: ["level1","profession"] },
  { spanish: "secretario(a)",      english: "secretary",        tags: ["level1","profession"] },
  { spanish: "trabajador(a) social",english: "social worker",   tags: ["level1","profession"] },
  { spanish: "vendedor(a)",        english: "salesperson",      tags: ["level1","profession"] },
  // ── Physical Adjectives (ser) ─────────────────────────────────────────
  { spanish: "alto(a)",            english: "tall",             tags: ["level1","adjective","physical"] },
  { spanish: "bajo(a)",            english: "short",            tags: ["level1","adjective","physical"] },
  { spanish: "bonito(a)",          english: "beautiful",        tags: ["level1","adjective","physical"] },
  { spanish: "calvo(a)",           english: "bald",             tags: ["level1","adjective","physical"] },
  { spanish: "de estatura media",  english: "medium height",    tags: ["level1","adjective","physical"] },
  { spanish: "de contextura media",english: "medium built",     tags: ["level1","adjective","physical"] },
  { spanish: "delgado(a)",         english: "slim",             tags: ["level1","adjective","physical"] },
  { spanish: "flaco(a)",           english: "skinny",           tags: ["level1","adjective","physical"] },
  { spanish: "feo(a)",             english: "ugly",             tags: ["level1","adjective","physical"] },
  { spanish: "gordo(a)",           english: "fat",              tags: ["level1","adjective","physical"] },
  { spanish: "grande",             english: "big",              tags: ["level1","adjective","physical"] },
  { spanish: "guapo(a)",           english: "good looking",     tags: ["level1","adjective","physical"] },
  { spanish: "joven",              english: "young",            tags: ["level1","adjective","physical"] },
  { spanish: "largo(a)",           english: "long",             tags: ["level1","adjective","physical"] },
  { spanish: "lindo(a)",           english: "cute",             tags: ["level1","adjective","physical"] },
  { spanish: "pequeño(a)",         english: "little",           tags: ["level1","adjective","physical"] },
  { spanish: "viejo(a)",           english: "old",              tags: ["level1","adjective","physical"] },
  // ── Personality Adjectives (ser) ──────────────────────────────────────
  { spanish: "aburrido(a)",        english: "boring",           tags: ["level1","adjective","personality"] },
  { spanish: "amable",             english: "kind",             tags: ["level1","adjective","personality"] },
  { spanish: "amigable",           english: "friendly",         tags: ["level1","adjective","personality"] },
  { spanish: "antipático(a)",      english: "unpleasant",       tags: ["level1","adjective","personality"] },
  { spanish: "atento(a)",          english: "attentive",        tags: ["level1","adjective","personality"] },
  { spanish: "bueno(a)",           english: "good",             tags: ["level1","adjective","personality"] },
  { spanish: "callado(a)",         english: "quiet",            tags: ["level1","adjective","personality"] },
  { spanish: "cariñoso(a)",        english: "affectionate",     tags: ["level1","adjective","personality"] },
  { spanish: "chistoso(a)",        english: "funny",            tags: ["level1","adjective","personality"] },
  { spanish: "divertido(a)",       english: "fun",              tags: ["level1","adjective","personality"] },
  { spanish: "extrovertido(a)",    english: "extroverted",      tags: ["level1","adjective","personality"] },
  { spanish: "inteligente",        english: "intelligent",      tags: ["level1","adjective","personality"] },
  { spanish: "interesante",        english: "interesting",      tags: ["level1","adjective","personality"] },
  { spanish: "listo(a)",           english: "smart",            tags: ["level1","adjective","personality"] },
  { spanish: "malo(a)",            english: "bad",              tags: ["level1","adjective","personality"] },
  { spanish: "paciente",           english: "patient",          tags: ["level1","adjective","personality"] },
  { spanish: "perezoso(a)",        english: "lazy",             tags: ["level1","adjective","personality"] },
  { spanish: "responsable",        english: "responsible",      tags: ["level1","adjective","personality"] },
  { spanish: "romántico(a)",       english: "romantic",         tags: ["level1","adjective","personality"] },
  { spanish: "serio(a)",           english: "serious",          tags: ["level1","adjective","personality"] },
  { spanish: "simpático(a)",       english: "nice",             tags: ["level1","adjective","personality"] },
  { spanish: "tierno(a)",          english: "loving",           tags: ["level1","adjective","personality"] },
  { spanish: "tímido(a)",          english: "shy",              tags: ["level1","adjective","personality"] },
  { spanish: "tonto(a)",           english: "dumb",             tags: ["level1","adjective","personality"] },
  { spanish: "trabajador(a)",      english: "hardworking",      tags: ["level1","adjective","personality"] },
  // ── Religion & Politics ───────────────────────────────────────────────
  { spanish: "bautista",           english: "baptist",          tags: ["level1","adjective","religion"] },
  { spanish: "católico(a)",        english: "catholic",         tags: ["level1","adjective","religion"] },
  { spanish: "judío(a)",           english: "jewish",           tags: ["level1","adjective","religion"] },
  { spanish: "luterano(a)",        english: "lutheran",         tags: ["level1","adjective","religion"] },
  { spanish: "metodista",          english: "methodist",        tags: ["level1","adjective","religion"] },
  { spanish: "musulmán(a)",        english: "muslim",           tags: ["level1","adjective","religion"] },
  { spanish: "protestante",        english: "protestant",       tags: ["level1","adjective","religion"] },
  { spanish: "cristiano",          english: "christian",        tags: ["level1","adjective","religion"] },
  { spanish: "demócrata",          english: "democrat",         tags: ["level1","adjective","politics"] },
  { spanish: "republicano(a)",     english: "republican",       tags: ["level1","adjective","politics"] },
  { spanish: "independiente",      english: "independent",      tags: ["level1","adjective","politics"] },
  // ── Colors ────────────────────────────────────────────────────────────
  { spanish: "amarillo(a)",        english: "yellow",           tags: ["level1","color","adjective"] },
  { spanish: "azul",               english: "blue",             tags: ["level1","color","adjective"] },
  { spanish: "beige",              english: "beige",            tags: ["level1","color","adjective"] },
  { spanish: "blanco(a)",          english: "white",            tags: ["level1","color","adjective"] },
  { spanish: "café",               english: "brown",            tags: ["level1","color","adjective"] },
  { spanish: "gris",               english: "grey",             tags: ["level1","color","adjective"] },
  { spanish: "morado(a)",          english: "purple",           tags: ["level1","color","adjective"] },
  { spanish: "naranja",            english: "orange",           tags: ["level1","color","adjective"] },
  { spanish: "negro(a)",           english: "black",            tags: ["level1","color","adjective"] },
  { spanish: "rojo(a)",            english: "red",              tags: ["level1","color","adjective"] },
  { spanish: "rosado(a)",          english: "pink",             tags: ["level1","color","adjective"] },
  { spanish: "verde",              english: "green",            tags: ["level1","color","adjective"] },
  // ── Family & Relationships ────────────────────────────────────────────
  { spanish: "abuelo(a)",          english: "grandfather/grandmother", tags: ["level1","family"] },
  { spanish: "amigo(a)",           english: "friend",           tags: ["level1","family"] },
  { spanish: "esposo(a)",          english: "spouse",           tags: ["level1","family"] },
  { spanish: "hermano(a)",         english: "brother/sister",   tags: ["level1","family"] },
  { spanish: "hijo(a)",            english: "son/daughter",     tags: ["level1","family"] },
  { spanish: "madre",              english: "mother",           tags: ["level1","family"] },
  { spanish: "novio(a)",           english: "boyfriend/girlfriend", tags: ["level1","family"] },
  { spanish: "padre",              english: "father",           tags: ["level1","family"] },
  { spanish: "primo(a)",           english: "cousin",           tags: ["level1","family"] },
  { spanish: "sobrino(a)",         english: "nephew/niece",     tags: ["level1","family"] },
  { spanish: "tío(a)",             english: "uncle/aunt",       tags: ["level1","family"] },
  { spanish: "prometida",          english: "fiancee",          tags: ["level1","family"] },
  { spanish: "yerno",              english: "son-in-law",       tags: ["level1","family"] },
  { spanish: "nuera",              english: "daughter-in-law",  tags: ["level1","family"] },
  { spanish: "suegro(a)",          english: "mother/father-in-law", tags: ["level1","family"] },
  // ── Materials ─────────────────────────────────────────────────────────
  { spanish: "algodón",            english: "cotton",           tags: ["level1","material"] },
  { spanish: "cuero",              english: "leather",          tags: ["level1","material"] },
  { spanish: "madera",             english: "wood",             tags: ["level1","material"] },
  { spanish: "metal",              english: "metal",            tags: ["level1","material"] },
  { spanish: "oro",                english: "gold",             tags: ["level1","material"] },
  { spanish: "plástico",           english: "plastic",          tags: ["level1","material"] },
  { spanish: "plata",              english: "silver",           tags: ["level1","material"] },
  { spanish: "seda",               english: "silk",             tags: ["level1","material"] },
  { spanish: "tela",               english: "fabric",           tags: ["level1","material"] },
  { spanish: "vidrio",             english: "glass",            tags: ["level1","material"] },
  // ── Days of the Week ──────────────────────────────────────────────────
  { spanish: "lunes",              english: "Monday",           tags: ["level1","days"] },
  { spanish: "martes",             english: "Tuesday",          tags: ["level1","days"] },
  { spanish: "miércoles",          english: "Wednesday",        tags: ["level1","days"] },
  { spanish: "jueves",             english: "Thursday",         tags: ["level1","days"] },
  { spanish: "viernes",            english: "Friday",           tags: ["level1","days"] },
  { spanish: "sábado",             english: "Saturday",         tags: ["level1","days"] },
  { spanish: "domingo",            english: "Sunday",           tags: ["level1","days"] },
  // ── Months ────────────────────────────────────────────────────────────
  { spanish: "enero",              english: "January",          tags: ["level1","months"] },
  { spanish: "febrero",            english: "February",         tags: ["level1","months"] },
  { spanish: "marzo",              english: "March",            tags: ["level1","months"] },
  { spanish: "abril",              english: "April",            tags: ["level1","months"] },
  { spanish: "mayo",               english: "May",              tags: ["level1","months"] },
  { spanish: "junio",              english: "June",             tags: ["level1","months"] },
  { spanish: "julio",              english: "July",             tags: ["level1","months"] },
  { spanish: "agosto",             english: "August",           tags: ["level1","months"] },
  { spanish: "septiembre",         english: "September",        tags: ["level1","months"] },
  { spanish: "octubre",            english: "October",          tags: ["level1","months"] },
  { spanish: "noviembre",          english: "November",         tags: ["level1","months"] },
  { spanish: "diciembre",          english: "December",         tags: ["level1","months"] },
  // ── Estar Adjectives (Emotional) ──────────────────────────────────────
  { spanish: "triste",             english: "sad",              tags: ["level1","adjective","emotion"] },
  { spanish: "feliz",              english: "happy",            tags: ["level1","adjective","emotion"] },
  { spanish: "cansado(a)",         english: "tired",            tags: ["level1","adjective","emotion"] },
  { spanish: "enfermo(a)",         english: "sick",             tags: ["level1","adjective","emotion"] },
  { spanish: "enojado(a)",         english: "angry",            tags: ["level1","adjective","emotion"] },
  { spanish: "nervioso(a)",        english: "nervous",          tags: ["level1","adjective","emotion"] },
  { spanish: "preocupado(a)",      english: "worried",          tags: ["level1","adjective","emotion"] },
  { spanish: "ocupado(a)",         english: "busy",             tags: ["level1","adjective","emotion"] },
  { spanish: "enamorado(a)",       english: "in love",          tags: ["level1","adjective","emotion"] },
  // ── Other Estar Adjectives ────────────────────────────────────────────
  { spanish: "descompuesto(a)",    english: "out of order",     tags: ["level1","adjective"] },
  { spanish: "desordenado(a)",     english: "unorganized",      tags: ["level1","adjective"] },
  { spanish: "ordenado(a)",        english: "neat",             tags: ["level1","adjective"] },
  { spanish: "limpio(a)",          english: "clean",            tags: ["level1","adjective"] },
  { spanish: "sucio(a)",           english: "dirty",            tags: ["level1","adjective"] },
  { spanish: "roto(a)",            english: "broken",           tags: ["level1","adjective"] },
  { spanish: "abierto(a)",         english: "open",             tags: ["level1","adjective"] },
  { spanish: "cerrado(a)",         english: "closed",           tags: ["level1","adjective"] },
  // ── El Cuerpo (Body) ──────────────────────────────────────────────────
  { spanish: "la cabeza",          english: "head",             tags: ["level2","body"] },
  { spanish: "el ojo",             english: "eye",              tags: ["level2","body"] },
  { spanish: "la nariz",           english: "nose",             tags: ["level2","body"] },
  { spanish: "la boca",            english: "mouth",            tags: ["level2","body"] },
  { spanish: "los labios",         english: "lips",             tags: ["level2","body"] },
  { spanish: "los dientes",        english: "teeth",            tags: ["level2","body"] },
  { spanish: "la lengua",          english: "tongue",           tags: ["level2","body"] },
  { spanish: "la oreja",           english: "ear (outer)",      tags: ["level2","body"] },
  { spanish: "el oído",            english: "ear (inner)",      tags: ["level2","body"] },
  { spanish: "la mejilla",         english: "cheek",            tags: ["level2","body"] },
  { spanish: "el pelo",            english: "hair",             tags: ["level2","body"] },
  { spanish: "el cabello",         english: "hair (head)",      tags: ["level2","body"] },
  { spanish: "la ceja",            english: "eyebrow",          tags: ["level2","body"] },
  { spanish: "las pestañas",       english: "eyelashes",        tags: ["level2","body"] },
  { spanish: "el mentón",          english: "chin",             tags: ["level2","body"] },
  { spanish: "la frente",          english: "forehead",         tags: ["level2","body"] },
  { spanish: "el cuello",          english: "neck",             tags: ["level2","body"] },
  { spanish: "la nuca",            english: "back of neck",     tags: ["level2","body"] },
  { spanish: "el hombro",          english: "shoulder",         tags: ["level2","body"] },
  { spanish: "el pecho",           english: "chest",            tags: ["level2","body"] },
  { spanish: "la espalda",         english: "back",             tags: ["level2","body"] },
  { spanish: "el brazo",           english: "arm",              tags: ["level2","body"] },
  { spanish: "el codo",            english: "elbow",            tags: ["level2","body"] },
  { spanish: "la muñeca",          english: "wrist",            tags: ["level2","body"] },
  { spanish: "la mano",            english: "hand",             tags: ["level2","body"] },
  { spanish: "el dedo",            english: "finger",           tags: ["level2","body"] },
  { spanish: "la uña",             english: "nail",             tags: ["level2","body"] },
  { spanish: "el estómago",        english: "stomach",          tags: ["level2","body"] },
  { spanish: "el ombligo",         english: "belly button",     tags: ["level2","body"] },
  { spanish: "las caderas",        english: "hips",             tags: ["level2","body"] },
  { spanish: "la cintura",         english: "waist",            tags: ["level2","body"] },
  { spanish: "los pompis",         english: "buns",             tags: ["level2","body"] },
  { spanish: "las nalgas",         english: "buns",             tags: ["level2","body"] },
  { spanish: "el muslo",           english: "thigh",            tags: ["level2","body"] },
  { spanish: "la pierna",          english: "leg",              tags: ["level2","body"] },
  { spanish: "la rodilla",         english: "knee",             tags: ["level2","body"] },
  { spanish: "el tobillo",         english: "ankle",            tags: ["level2","body"] },
  { spanish: "el pie",             english: "foot",             tags: ["level2","body"] },
  { spanish: "el dedo del pie",    english: "toe",              tags: ["level2","body"] },
  { spanish: "la planta del pie",  english: "bottom of foot",   tags: ["level2","body"] },

  // ── Tener expressions ────────────────────────────────────────────────
  { spanish: "tener",              english: "to have",           tags: ["level2","verb","tener"] },
  { spanish: "ir",                 english: "to go",             tags: ["level2","verb"] },
  { spanish: "tener hambre",       english: "to be hungry",      tags: ["level2","verb","tener"] },
  { spanish: "tener sed",          english: "to be thirsty",     tags: ["level2","verb","tener"] },
  { spanish: "tener frío",         english: "to be cold",        tags: ["level2","verb","tener"] },
  { spanish: "tener calor",        english: "to be hot",         tags: ["level2","verb","tener"] },
  { spanish: "tener prisa",        english: "to be in a hurry",  tags: ["level2","verb","tener"] },
  { spanish: "tener miedo",        english: "to be afraid",      tags: ["level2","verb","tener"] },
  { spanish: "tener sueño",        english: "to be sleepy",      tags: ["level2","verb","tener"] },
  { spanish: "tener ganas de",     english: "to feel like",      tags: ["level2","verb","tener"] },
  { spanish: "tener razón",        english: "to be correct",     tags: ["level2","verb","tener"] },
  { spanish: "tener suerte",       english: "to be lucky",       tags: ["level2","verb","tener"] },
  { spanish: "tener éxito",        english: "to be successful",  tags: ["level2","verb","tener"] },

  // ── Family (individual forms) ────────────────────────────────────────────
  { spanish: "madre",              english: "mother",            tags: ["level2","family"] },
  { spanish: "padre",              english: "father",            tags: ["level2","family"] },
  { spanish: "hijo",               english: "son",               tags: ["level2","family"] },
  { spanish: "hija",               english: "daughter",          tags: ["level2","family"] },
  { spanish: "hermano",            english: "brother",           tags: ["level2","family"] },
  { spanish: "hermana",            english: "sister",            tags: ["level2","family"] },
  { spanish: "tío",                english: "uncle",             tags: ["level2","family"] },
  { spanish: "tía",                english: "aunt",              tags: ["level2","family"] },
  { spanish: "sobrino",            english: "nephew",            tags: ["level2","family"] },
  { spanish: "sobrina",            english: "niece",             tags: ["level2","family"] },
  { spanish: "esposo",             english: "husband",           tags: ["level2","family"] },
  { spanish: "esposa",             english: "wife",              tags: ["level2","family"] },
  { spanish: "abuelo",             english: "grandfather",       tags: ["level2","family"] },
  { spanish: "abuela",             english: "grandmother",       tags: ["level2","family"] },
  { spanish: "bisabuelo",          english: "great grandfather", tags: ["level2","family"] },
  { spanish: "bisabuela",          english: "great grandmother", tags: ["level2","family"] },
  { spanish: "nieto",              english: "grandson",          tags: ["level2","family"] },
  { spanish: "nieta",              english: "granddaughter",     tags: ["level2","family"] },
  { spanish: "suegro",             english: "father-in-law",     tags: ["level2","family"] },
  { spanish: "suegra",             english: "mother-in-law",     tags: ["level2","family"] },
  { spanish: "cuñado",             english: "brother-in-law",    tags: ["level2","family"] },
  { spanish: "cuñada",             english: "sister-in-law",     tags: ["level2","family"] },
  { spanish: "padrastro",          english: "step father",       tags: ["level2","family"] },
  { spanish: "madrastra",          english: "step mother",       tags: ["level2","family"] },
  { spanish: "primo(a)",           english: "cousin",            tags: ["level2","family"] },
  { spanish: "yerno",              english: "son-in-law",        tags: ["level2","family"] },
  { spanish: "nuera",              english: "daughter-in-law",   tags: ["level2","family"] },
  { spanish: "hijastro",           english: "step-son",          tags: ["level2","family"] },
  { spanish: "hijastra",           english: "step-daughter",     tags: ["level2","family"] },
  { spanish: "los parientes",      english: "relatives",         tags: ["level2","family"] },
];

async function seedIfEmpty() {
  const seeded = await DB.getSetting('seeded');
  if (seeded === 'v9') return;

  const existing = await DB.getAllCards();
  const existingBySpanish = new Map(existing.map(c => [c.spanish.toLowerCase(), c]));

  for (const seed of SEED_CARDS) {
    const key = seed.spanish.toLowerCase();
    if (existingBySpanish.has(key)) {
      const card = existingBySpanish.get(key);
      await DB.updateCard(card.id, { tags: seed.tags });
    } else {
      await DB.createCard({ ...seed, notes: '' });
    }
  }

  await DB.setSetting('seeded', 'v9');
  console.log('Seed v9 complete.');
}

window.seedIfEmpty = seedIfEmpty;
